var searchData=
[
  ['b_3a_20plain_20cmake_20with_20existing_20dependencies_0',['Option B: Plain CMake with existing dependencies',['../user_installation.html#autotoc_md630',1,'']]],
  ['backpressure_20best_20practices_1',['3. Backpressure Best Practices',['../contrib_arch_runtime.html#autotoc_md234',1,'']]],
  ['backpressure_20configuration_2',['Backpressure Configuration',['../contrib_arch_runtime.html#autotoc_md212',1,'']]],
  ['backpressure_20flow_3',['Backpressure Flow',['../contrib_arch_runtime.html#autotoc_md210',1,'']]],
  ['backpressure_20handling_4',['Backpressure Handling',['../contrib_arch_runtime.html#autotoc_md209',1,'']]],
  ['backpressure_20management_5',['Backpressure Management',['../user_performance.html#backpressure-management',1,'']]],
  ['backpressure_20monitoring_6',['Backpressure Monitoring',['../contrib_arch_runtime.html#autotoc_md221',1,'']]],
  ['backpressure_20overhead_7',['Backpressure Overhead',['../contrib_arch_runtime.html#autotoc_md241',1,'']]],
  ['backpressure_20policy_8',['4. Backpressure Policy',['../contrib_arch_channel.html#autotoc_md6',1,'']]],
  ['backpressure_20semantics_9',['Send And Backpressure Semantics',['../user_api_guide.html#autotoc_md590',1,'']]],
  ['backpressure_20strategies_10',['Backpressure Strategies',['../contrib_arch_runtime.html#autotoc_md214',1,'']]],
  ['backpressure_20strategy_11',['Backpressure Strategy',['../user_api_guide.html#autotoc_md588',1,'']]],
  ['backpressure_20support_12',['Backpressure Support',['../user_transport_matrix.html#autotoc_md725',1,'']]],
  ['backpressure_5fstrategy_13',['backpressure_strategy',['../classunilink_1_1builder_1_1BuilderInterface.html#a488d998ee718a02a3b4c4f8a144131bb',1,'unilink::builder::BuilderInterface']]],
  ['backpressure_5fthreshold_14',['backpressure_threshold',['../classunilink_1_1builder_1_1BuilderInterface.html#a006597a9daa6b0e6dbc618775978a09a',1,'unilink::builder::BuilderInterface']]],
  ['backpressurefields_15',['BackpressureFields',['../structunilink_1_1transport_1_1queue__util_1_1BackpressureFields.html',1,'unilink::transport::queue_util']]],
  ['basic_20build_20recommended_16',['Basic Build (Recommended)',['../contrib_build.html#autotoc_md262',1,'']]],
  ['basic_20usage_17',['basic usage',['../user_api_guide.html#autotoc_md515',1,'Basic Usage'],['../user_api_guide.html#autotoc_md526',1,'Basic Usage'],['../user_api_guide.html#autotoc_md537',1,'Basic Usage'],['../user_api_guide.html#autotoc_md550',1,'Basic Usage'],['../user_api_guide.html#autotoc_md567',1,'Basic Usage'],['../user_api_guide.html#autotoc_md505',1,'Basic Usage']]],
  ['batch_20small_20messages_18',['batch small messages',['../user_performance.html#autotoc_md656',1,'1. Batch Small Messages'],['../user_troubleshooting.html#autotoc_md794',1,'1. Batch Small Messages']]],
  ['be_20reused_19',['4. Externally supplied &lt;tt&gt;io_context&lt;/tt&gt; can be reused',['../contrib_arch_wrapper.html#autotoc_md250',1,'']]],
  ['before_20v1_200_20',['Internal Or Not Source-Stable Before v1.0',['../user_api_stability.html#autotoc_md606',1,'']]],
  ['behavior_21',['behavior',['../contrib_arch_runtime.html#autotoc_md195',1,'Default Behavior'],['../contrib_arch_runtime.html#autotoc_md194',1,'Retry Behavior']]],
  ['behavior_20model_22',['Runtime Behavior Model',['../contrib_arch_runtime.html',1,'contrib_arch']]],
  ['being_20called_23',['Problem: Callbacks Not Being Called',['../user_troubleshooting.html#autotoc_md776',1,'']]],
  ['benchmarking_24',['Benchmarking',['../contrib_testing.html#autotoc_md435',1,'']]],
  ['benefits_25',['Memory Safety Benefits',['../contrib_arch_memory.html#autotoc_md84',1,'']]],
  ['best_20practices_26',['best practices',['../contrib_arch_runtime.html#autotoc_md226',1,'1. Threading Best Practices'],['../contrib_arch_runtime.html#autotoc_md230',1,'2. Reconnection Best Practices'],['../contrib_arch_runtime.html#autotoc_md234',1,'3. Backpressure Best Practices'],['../user_api_guide.html#autotoc_md577',1,'Best Practices'],['../contrib_arch_runtime.html#autotoc_md225',1,'Best Practices'],['../contrib_arch_memory.html#autotoc_md63',1,'Best Practices'],['../contrib_arch_runtime.html#autotoc_md202',1,'Reconnection Best Practices']]],
  ['besteffort_27',['BestEffort',['../user_api_guide.html#autotoc_md592',1,'']]],
  ['besteffort_20semantics_28',['BestEffort Semantics',['../contrib_design_send_result.html#autotoc_md345',1,'']]],
  ['binary_20protocol_29',['2. Use Binary Protocol',['../user_troubleshooting.html#autotoc_md795',1,'']]],
  ['binding_20failures_30',['Port-Binding Failures',['../contrib_orin_nano_validation.html#autotoc_md389',1,'']]],
  ['binding_20scope_31',['Python Binding Scope',['../contrib_impl_status.html#autotoc_md357',1,'']]],
  ['bindings_32',['bindings',['../user_api_stability.html#autotoc_md611',1,'Python Bindings'],['../user_python_bindings.html',1,'Python Bindings']]],
  ['block_20in_20callbacks_33',['⚠️ Never Block in Callbacks',['../contrib_arch_runtime.html#autotoc_md181',1,'']]],
  ['blocking_34',['3. Firewall Blocking',['../user_troubleshooting.html#autotoc_md739',1,'']]],
  ['blocking_20callbacks_35',['3. Non-Blocking Callbacks',['../user_performance.html#autotoc_md649',1,'']]],
  ['blocking_20startup_36',['1. Non-Blocking Startup',['../user_tutorial_async.html#autotoc_md893',1,'']]],
  ['bool_20api_37',['Current bool API',['../contrib_design_send_result.html#autotoc_md337',1,'']]],
  ['boost_38',['Problem: CMake Can&apos;t Find Boost',['../contrib_build.html#autotoc_md324',1,'']]],
  ['boost_20location_39',['Example 4: Build with Custom Boost Location',['../contrib_build.html#autotoc_md290',1,'']]],
  ['boost_20not_20found_40',['boost not found',['../contrib_orin_nano_validation.html#autotoc_md387',1,'Boost Not Found'],['../user_troubleshooting.html#autotoc_md765',1,'Problem: Boost Not Found'],['../user_requirements.html#autotoc_md716',1,'Problem: Boost Not Found']]],
  ['boost_20path_41',['Manual Boost Path',['../user_troubleshooting.html#autotoc_md769',1,'']]],
  ['boost_20setup_42',['System Boost setup',['../user_troubleshooting.html#autotoc_md767',1,'']]],
  ['boost_20version_43',['Check Boost Version',['../user_requirements.html#autotoc_md711',1,'']]],
  ['boostserialport_44',['BoostSerialPort',['../classunilink_1_1transport_1_1BoostSerialPort.html',1,'unilink::transport']]],
  ['boosttcpacceptor_45',['BoostTcpAcceptor',['../classunilink_1_1transport_1_1BoostTcpAcceptor.html',1,'unilink::transport']]],
  ['boosttcpsocket_46',['BoostTcpSocket',['../classunilink_1_1transport_1_1BoostTcpSocket.html',1,'unilink::transport']]],
  ['boostudsacceptor_47',['BoostUdsAcceptor',['../classunilink_1_1transport_1_1BoostUdsAcceptor.html',1,'unilink::transport']]],
  ['boostudssocket_48',['BoostUdsSocket',['../classunilink_1_1transport_1_1BoostUdsSocket.html',1,'unilink::transport']]],
  ['both_20programs_49',['Step 4: Run Both Programs',['../tutorial_05.html#autotoc_md882',1,'']]],
  ['broad_20category_50',['Run By Broad Category',['../contrib_test_structure.html#autotoc_md404',1,'']]],
  ['broadcast_51',['broadcast',['../classunilink_1_1wrapper_1_1ServerInterface.html#a2264498ef97a2d7b609557afc46754f9',1,'unilink::wrapper::ServerInterface::broadcast()'],['../classunilink_1_1wrapper_1_1TcpServer.html#a45b4eb1fb1e8cd8786bf240b765d7181',1,'unilink::wrapper::TcpServer::broadcast()'],['../classunilink_1_1wrapper_1_1UdpServer.html#aeb4e4ccfc8c7f547696756aa3b444d9f',1,'unilink::wrapper::UdpServer::broadcast()'],['../classunilink_1_1wrapper_1_1UdsServer.html#a43983c237bfa6949654c1248c75e8dfe',1,'unilink::wrapper::UdsServer::broadcast()']]],
  ['broadcast_5fline_52',['broadcast_line',['../classunilink_1_1wrapper_1_1ServerInterface.html#a914beef46c8740d068ea44c2918c7685',1,'unilink::wrapper::ServerInterface::broadcast_line()'],['../classunilink_1_1wrapper_1_1TcpServer.html#ae1575d3f34f582f2c0a40c260ead4c04',1,'unilink::wrapper::TcpServer::broadcast_line()'],['../classunilink_1_1wrapper_1_1UdpServer.html#a9497a7bbeb4a53c57bec6da015ce1e2f',1,'unilink::wrapper::UdpServer::broadcast_line()'],['../classunilink_1_1wrapper_1_1UdsServer.html#a1f33f49e6511858698e6b5c0b67faa16',1,'unilink::wrapper::UdsServer::broadcast_line()']]],
  ['buffer_53',['4. Safe Data Buffer',['../contrib_arch.html#autotoc_md138',1,'']]],
  ['buffer_20management_54',['1. Buffer Management',['../contrib_arch_memory.html#autotoc_md64',1,'']]],
  ['buffer_20sends_55',['Move And Shared Buffer Sends',['../user_api_guide.html#autotoc_md498',1,'']]],
  ['buffer_20sizes_56',['3. Limit Buffer Sizes',['../user_troubleshooting.html#autotoc_md791',1,'']]],
  ['build_57',['build',['../classunilink_1_1builder_1_1UdsServerBuilder.html#a157983ec61893d6409835e9ab0cf39ac',1,'unilink::builder::UdsServerBuilder::build()'],['../classunilink_1_1builder_1_1TcpServerBuilder.html#a0c0029f7ca4b8ae9bf08f467a1b2348c',1,'unilink::builder::TcpServerBuilder::build()'],['../classunilink_1_1builder_1_1BuilderInterface.html#ac820ef71f8275a33d1816c43c20df754',1,'unilink::builder::BuilderInterface::build()'],['../classunilink_1_1builder_1_1UdpClientBuilder.html#a995fddcda154abf3bec6664c6b3bbf7f',1,'unilink::builder::UdpClientBuilder::build()'],['../classunilink_1_1builder_1_1SerialBuilder.html#aa804e78bd46394d49545000cca88c77a',1,'unilink::builder::SerialBuilder::build()'],['../classunilink_1_1builder_1_1UdsClientBuilder.html#a0a77bbeded5fea6aa9723b8367786e17',1,'unilink::builder::UdsClientBuilder::build()'],['../classunilink_1_1builder_1_1UdpServerBuilder.html#a3744aefd31e004c515e0e6a1340e45f0',1,'unilink::builder::UdpServerBuilder::build()'],['../classunilink_1_1builder_1_1TcpClientBuilder.html#a3209a5f18973c46d60299428afcc4e62',1,'unilink::builder::TcpClientBuilder::build()'],['../contrib_orin_nano_validation.html#autotoc_md375',1,'Configure And Build'],['../contrib_build.html#autotoc_md279',1,'Debug Build'],['../contrib_build.html#autotoc_md284',1,'Example 1: Minimal Production Build'],['../contrib_build.html#autotoc_md286',1,'Example 2: Development Build'],['../contrib_build.html#autotoc_md326',1,'Problem: Out of Memory During Build'],['../contrib_build.html#autotoc_md261',1,'Quick Build'],['../contrib_build.html#autotoc_md281',1,'RelWithDebInfo Build'],['../contrib_build.html#autotoc_md297',1,'Ubuntu 20.04 Build'],['../contrib_build.html#autotoc_md318',1,'Verifying the Build'],['../tutorial_02.html#autotoc_md829',1,'What You&apos;ll Build'],['../tutorial_01.html#autotoc_md814',1,'What You&apos;ll Build'],['../tutorial_03.html#autotoc_md844',1,'What You&apos;ll Build'],['../tutorial_04.html#autotoc_md857',1,'What You&apos;ll Build'],['../tutorial_05.html#autotoc_md874',1,'What You&apos;ll Build']]],
  ['build_20and_20run_58',['Step 3: Build And Run',['../tutorial_04.html#autotoc_md863',1,'']]],
  ['build_20and_20run_20all_20tests_59',['Build and Run All Tests',['../contrib_testing.html#autotoc_md413',1,'']]],
  ['build_20and_20test_60',['2. Build And Test',['../contrib_release_checklist.html#autotoc_md393',1,'']]],
  ['build_20and_20test_20status_61',['Build And Test Status',['../contrib_impl_status.html#autotoc_md358',1,'']]],
  ['build_20configurations_62',['Build Configurations',['../contrib_build.html#autotoc_md266',1,'']]],
  ['build_20default_63',['Release Build (Default)',['../contrib_build.html#autotoc_md277',1,'']]],
  ['build_20examples_64',['Advanced Build Examples',['../contrib_build.html#autotoc_md283',1,'']]],
  ['build_20guide_65',['Build Guide',['../contrib_build.html',1,'contrib_index']]],
  ['build_20includes_20configuration_20management_20api_66',['Full Build (includes Configuration Management API)',['../contrib_build.html#autotoc_md269',1,'']]],
  ['build_20matrix_67',['CI/CD Build Matrix',['../contrib_testing.html#autotoc_md451',1,'']]],
  ['build_20notes_68',['Important Build Notes',['../contrib_build.html#autotoc_md264',1,'']]],
  ['build_20options_20reference_69',['Build Options Reference',['../contrib_build.html#autotoc_md271',1,'']]],
  ['build_20options_20source_20builds_70',['Build Options (Source Builds)',['../user_installation.html#autotoc_md641',1,'']]],
  ['build_20performance_20tips_71',['Build Performance Tips',['../contrib_build.html#autotoc_md308',1,'']]],
  ['build_20recommended_72',['Basic Build (Recommended)',['../contrib_build.html#autotoc_md262',1,'']]],
  ['build_20steps_73',['Build Steps',['../contrib_build.html#autotoc_md299',1,'']]],
  ['build_20system_20faster_20than_20make_74',['Ninja Build System (Faster than Make)',['../contrib_build.html#autotoc_md311',1,'']]],
  ['build_20test_20workflow_75',['Windows Build &amp; Test Workflow',['../contrib_testing.html#autotoc_md415',1,'']]],
  ['build_20the_20two_20programs_76',['Step 3: Build The Two Programs',['../tutorial_05.html#autotoc_md880',1,'']]],
  ['build_20time_20controls_77',['Build-Time Controls',['../contrib_test_structure.html#autotoc_md401',1,'']]],
  ['build_20types_20comparison_78',['Build Types Comparison',['../contrib_build.html#autotoc_md276',1,'']]],
  ['build_20vcpkg_20setup_79',['Source-build vcpkg setup',['../user_troubleshooting.html#autotoc_md766',1,'']]],
  ['build_20with_20cmake_80',['Step 2: Build With CMake',['../tutorial_01.html#autotoc_md818',1,'']]],
  ['build_20with_20custom_20boost_20location_81',['Example 4: Build with Custom Boost Location',['../contrib_build.html#autotoc_md290',1,'']]],
  ['build_20with_20specific_20compiler_82',['Example 5: Build with Specific Compiler',['../contrib_build.html#autotoc_md292',1,'']]],
  ['build_20without_20configuration_20management_20api_83',['Minimal Build (without Configuration Management API)',['../contrib_build.html#autotoc_md267',1,'']]],
  ['builder_20api_84',['Builder API',['../user_api_guide.html#autotoc_md492',1,'']]],
  ['builder_20api_20layer_85',['1. Builder API Layer',['../contrib_arch.html#autotoc_md105',1,'']]],
  ['builder_20methods_86',['builder methods',['../user_api_guide.html#autotoc_md529',1,'Builder Methods'],['../user_api_guide.html#autotoc_md518',1,'Builder Methods'],['../user_api_guide.html#autotoc_md508',1,'Builder Methods']]],
  ['builder_20methods_20udpclient_87',['Builder Methods (UdpClient)',['../user_api_guide.html#autotoc_md542',1,'']]],
  ['builder_20methods_20udpserver_88',['Builder Methods (UdpServer)',['../user_api_guide.html#autotoc_md543',1,'']]],
  ['builder_20methods_20uds_20client_89',['Builder Methods (UDS Client)',['../user_api_guide.html#autotoc_md556',1,'']]],
  ['builder_20methods_20uds_20server_90',['Builder Methods (UDS Server)',['../user_api_guide.html#autotoc_md555',1,'']]],
  ['builder_20pattern_91',['1. Builder Pattern',['../contrib_arch.html#autotoc_md117',1,'']]],
  ['builder_20system_92',['1. Builder System',['../contrib_arch.html#autotoc_md111',1,'']]],
  ['builderexception_93',['BuilderException',['../classunilink_1_1diagnostics_1_1BuilderException.html',1,'unilink::diagnostics']]],
  ['builderinterface_94',['BuilderInterface',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3aserial_2c_20serialbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_95',['BuilderInterface&lt; wrapper::Serial, SerialBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3atcpclient_2c_20tcpclientbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_96',['BuilderInterface&lt; wrapper::TcpClient, TcpClientBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3atcpserver_2c_20tcpserverbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_97',['BuilderInterface&lt; wrapper::TcpServer, TcpServerBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3audpclient_2c_20udpclientbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_98',['BuilderInterface&lt; wrapper::UdpClient, UdpClientBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3audpserver_2c_20udpserverbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_99',['BuilderInterface&lt; wrapper::UdpServer, UdpServerBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3audsclient_2c_20udsclientbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_100',['BuilderInterface&lt; wrapper::UdsClient, UdsClientBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builderinterface_3c_20wrapper_3a_3audsserver_2c_20udsserverbuilder_3c_20builderstate_3a_3anone_20_3e_2c_20builderstate_3a_3anone_20_3e_101',['BuilderInterface&lt; wrapper::UdsServer, UdsServerBuilder&lt; BuilderState::None &gt;, BuilderState::None &gt;',['../classunilink_1_1builder_1_1BuilderInterface.html',1,'unilink::builder']]],
  ['builders_102',['builders',['../contrib_arch.html#autotoc_md157',1,'2. Custom Builders'],['../user_api_guide.html#autotoc_md494',1,'Common Methods (All Builders)']]],
  ['building_20a_20tcp_20server_103',['Building a TCP Server',['../tutorial_02.html',1,'user_tutorials']]],
  ['building_20the_20library_104',['Building the Library',['../contrib_index.html#autotoc_md361',1,'']]],
  ['builds_105',['builds',['../user_installation.html#autotoc_md641',1,'Build Options (Source Builds)'],['../contrib_build.html#autotoc_md309',1,'Parallel Builds'],['../contrib_build.html#autotoc_md294',1,'Platform-Specific Builds']]],
  ['builds_20with_20vcpkg_106',['Windows source builds with vcpkg',['../user_troubleshooting.html#autotoc_md768',1,'']]],
  ['built_20in_20memory_20tracking_107',['built in memory tracking',['../contrib_testing.html#autotoc_md440',1,'Built-in Memory Tracking'],['../contrib_arch_memory.html#autotoc_md41',1,'Built-in Memory Tracking']]],
  ['busy_20loop_20in_20callback_108',['1. Busy Loop in Callback',['../user_troubleshooting.html#autotoc_md785',1,'']]],
  ['but_20advanced_20headers_109',['Supported But Advanced Headers',['../user_api_stability.html#autotoc_md605',1,'']]],
  ['by_20broad_20category_110',['Run By Broad Category',['../contrib_test_structure.html#autotoc_md404',1,'']]]
];
