var searchData=
[
  ['v1_200_0',['Internal Or Not Source-Stable Before v1.0',['../user_api_stability.html#autotoc_md606',1,'']]],
  ['valgrind_1',['Valgrind',['../contrib_testing.html#autotoc_md446',1,'']]],
  ['validate_20all_20input_2',['Validate All Input',['../user_api_guide.html#autotoc_md601',1,'']]],
  ['validate_5fcanary_5fbytes_3',['validate_canary_bytes',['../namespaceunilink_1_1memory_1_1memory__validator.html#a5acf0c8d036313b53f32346afd80f5a3',1,'unilink::memory::memory_validator']]],
  ['validation_4',['validation',['../contrib_arch_memory.html#autotoc_md21',1,'1. Construction Validation'],['../contrib_arch_memory.html#autotoc_md25',1,'3. Memory Validation'],['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2README.html#autotoc_md906',1,'Local validation'],['../contrib_testing.html#autotoc_md439',1,'Memory Safety Validation'],['../contrib_orin_nano_validation.html',1,'Orin Nano Validation'],['../contrib_orin_nano_validation.html#autotoc_md379',1,'Serial Validation']]],
  ['validation_20snapshot_5',['Latest Validation Snapshot',['../contrib_orin_nano_validation.html#autotoc_md371',1,'']]],
  ['validationexception_6',['ValidationException',['../classunilink_1_1diagnostics_1_1ValidationException.html',1,'unilink::diagnostics']]],
  ['validationresult_7',['ValidationResult',['../structunilink_1_1config_1_1ValidationResult.html',1,'unilink::config']]],
  ['variables_8',['Environment Variables',['../contrib_testing.html#autotoc_md467',1,'']]],
  ['vcpkg_9',['vcpkg',['../user_installation.html#autotoc_md626',1,'Step 1: Install via vcpkg'],['../user_troubleshooting.html#autotoc_md768',1,'Windows source builds with vcpkg']]],
  ['vcpkg_20recommended_10',['Method 1: vcpkg (Recommended)',['../user_installation.html#autotoc_md625',1,'']]],
  ['vcpkg_20setup_11',['vcpkg setup',['../user_installation.html#autotoc_md629',1,'Option A: Repository-managed vcpkg setup'],['../user_troubleshooting.html#autotoc_md766',1,'Source-build vcpkg setup']]],
  ['vcpkg_20toolchain_12',['Option C: Plain CMake with vcpkg toolchain',['../user_installation.html#autotoc_md631',1,'']]],
  ['vector_20capacity_13',['2. Reserve Vector Capacity',['../user_performance.html#autotoc_md653',1,'']]],
  ['verbose_20output_14',['Run Tests with Verbose Output',['../contrib_testing.html#autotoc_md422',1,'']]],
  ['verification_15',['verification',['../contrib_arch.html#autotoc_md166',1,'3. State Verification'],['../contrib_build.html#autotoc_md333',1,'Verification']]],
  ['verifying_20the_20build_16',['Verifying the Build',['../contrib_build.html#autotoc_md318',1,'']]],
  ['verifying_20your_20environment_17',['Verifying Your Environment',['../user_requirements.html#autotoc_md708',1,'']]],
  ['version_18',['version',['../user_requirements.html#autotoc_md711',1,'Check Boost Version'],['../user_requirements.html#autotoc_md710',1,'Check CMake Version'],['../user_requirements.html#autotoc_md709',1,'Check Compiler Version']]],
  ['versioning_19',['1. Versioning',['../contrib_release_checklist.html#autotoc_md392',1,'']]],
  ['versions_20',['Minimum Compiler Versions',['../user_requirements.html#autotoc_md695',1,'']]],
  ['via_20vcpkg_21',['Step 1: Install via vcpkg',['../user_installation.html#autotoc_md626',1,'']]],
  ['view_20ci_20cd_20results_22',['View CI/CD Results',['../contrib_testing.html#autotoc_md455',1,'']]],
  ['view_20html_20coverage_20report_23',['View HTML Coverage Report',['../contrib_testing.html#autotoc_md480',1,'']]],
  ['virtual_20serial_20pair_24',['Manual Virtual Serial Pair',['../contrib_orin_nano_validation.html#autotoc_md381',1,'']]],
  ['vs_20asynchronously_25',['Starting Synchronously vs. Asynchronously',['../user_api_guide.html#autotoc_md501',1,'']]],
  ['vs_20sync_26',['4. When to Use Async vs Sync',['../user_tutorial_async.html#autotoc_md901',1,'']]],
  ['vulnerabilities_27',['Prevents Common Vulnerabilities',['../contrib_arch_memory.html#autotoc_md85',1,'']]]
];
