var searchData=
[
  ['want_20more_0',['Use The Full Example If You Want More',['../tutorial_01.html#autotoc_md824',1,'']]],
  ['what_20asan_20detects_1',['What ASan Detects',['../contrib_arch_memory.html#autotoc_md57',1,'']]],
  ['what_20each_20area_20covers_2',['What Each Area Covers',['../contrib_test_structure.html#autotoc_md400',1,'']]],
  ['what_20is_20currently_20registered_3',['Inspect What Is Currently Registered',['../contrib_test_structure.html#autotoc_md406',1,'']]],
  ['what_20is_20different_20about_20udp_4',['What Is Different About UDP',['../tutorial_05.html#autotoc_md884',1,'']]],
  ['what_20you_20ll_20build_5',['what you ll build',['../tutorial_05.html#autotoc_md874',1,'What You&apos;ll Build'],['../tutorial_04.html#autotoc_md857',1,'What You&apos;ll Build'],['../tutorial_03.html#autotoc_md844',1,'What You&apos;ll Build'],['../tutorial_02.html#autotoc_md829',1,'What You&apos;ll Build'],['../tutorial_01.html#autotoc_md814',1,'What You&apos;ll Build']]],
  ['when_20to_20use_20async_20vs_20sync_6',['4. When to Use Async vs Sync',['../user_tutorial_async.html#autotoc_md901',1,'']]],
  ['when_20to_20use_20each_7',['When to use each',['../user_api_guide.html#autotoc_md595',1,'']]],
  ['when_20to_20use_20the_20example_20programs_20instead_8',['When To Use The Example Programs Instead',['../tutorial_04.html#autotoc_md869',1,'']]],
  ['why_20use_20uds_20instead_20of_20tcp_9',['Why Use UDS Instead Of TCP',['../tutorial_03.html#autotoc_md850',1,'']]],
  ['wide_20installation_10',['System-Wide Installation',['../contrib_build.html#autotoc_md314',1,'']]],
  ['windows_20build_20test_20workflow_11',['Windows Build &amp; Test Workflow',['../contrib_testing.html#autotoc_md415',1,'']]],
  ['windows_20source_20builds_20with_20vcpkg_12',['Windows source builds with vcpkg',['../user_troubleshooting.html#autotoc_md768',1,'']]],
  ['with_20a_20second_20terminal_13',['Step 4: Test With A Second Terminal',['../tutorial_04.html#autotoc_md865',1,'']]],
  ['with_20asan_14',['Running with ASan',['../contrib_arch_memory.html#autotoc_md59',1,'']]],
  ['with_20cmake_15',['Step 2: Build With CMake',['../tutorial_01.html#autotoc_md818',1,'']]],
  ['with_20custom_20boost_20location_16',['Example 4: Build with Custom Boost Location',['../contrib_build.html#autotoc_md290',1,'']]],
  ['with_20existing_20dependencies_17',['Option B: Plain CMake with existing dependencies',['../user_installation.html#autotoc_md630',1,'']]],
  ['with_20lambda_20capture_18',['With Lambda Capture',['../user_api_guide.html#autotoc_md512',1,'']]],
  ['with_20member_20functions_19',['With Member Functions',['../user_api_guide.html#autotoc_md511',1,'']]],
  ['with_20netcat_20',['Test with netcat',['../user_troubleshooting.html#autotoc_md809',1,'']]],
  ['with_20reliable_20strategy_20still_20drops_20packets_21',['Problem: UDP with Reliable Strategy Still Drops Packets',['../user_troubleshooting.html#autotoc_md781',1,'']]],
  ['with_20sanitizers_22',['Example 3: Testing with Sanitizers',['../contrib_build.html#autotoc_md288',1,'']]],
  ['with_20specific_20compiler_23',['Example 5: Build with Specific Compiler',['../contrib_build.html#autotoc_md292',1,'']]],
  ['with_20tcpdump_24',['Network Debugging with tcpdump',['../user_troubleshooting.html#autotoc_md808',1,'']]],
  ['with_20unilink_25',['Getting Started with Unilink',['../tutorial_01.html',1,'user_tutorials']]],
  ['with_20vcpkg_26',['Windows source builds with vcpkg',['../user_troubleshooting.html#autotoc_md768',1,'']]],
  ['with_20vcpkg_20toolchain_27',['Option C: Plain CMake with vcpkg toolchain',['../user_installation.html#autotoc_md631',1,'']]],
  ['with_20verbose_20output_28',['Run Tests with Verbose Output',['../contrib_testing.html#autotoc_md422',1,'']]],
  ['without_20configuration_20management_20api_29',['Minimal Build (without Configuration Management API)',['../contrib_build.html#autotoc_md267',1,'']]],
  ['workflow_30',['Windows Build &amp; Test Workflow',['../contrib_testing.html#autotoc_md415',1,'']]],
  ['wrapper_20api_20layer_31',['2. Wrapper API Layer',['../contrib_arch.html#autotoc_md106',1,'']]],
  ['wrapper_20callbacks_20after_20tt_20stop_20tt_20returns_32',['7. No wrapper callbacks after &lt;tt&gt;stop()&lt;/tt&gt; returns',['../contrib_arch_wrapper.html#autotoc_md254',1,'']]],
  ['wrapper_20contract_33',['Wrapper Contract',['../contrib_arch_wrapper.html',1,'contrib_arch']]],
  ['wrapper_20system_34',['2. Wrapper System',['../contrib_arch.html#autotoc_md112',1,'']]],
  ['writing_20custom_20tests_35',['Writing Custom Tests',['../contrib_testing.html#autotoc_md457',1,'']]],
  ['wrong_20host_20port_36',['2. Wrong Host/Port',['../user_troubleshooting.html#autotoc_md738',1,'']]]
];
