var searchData=
[
  ['package_0',['Using the Installed Package',['../contrib_build.html#autotoc_md330',1,'']]],
  ['package_20components_1',['Package Components',['../contrib_build.html#autotoc_md332',1,'']]],
  ['package_20integration_2',['CMake Package Integration',['../contrib_build.html#autotoc_md329',1,'']]],
  ['packages_3',['Method 3: Release Packages',['../user_installation.html#autotoc_md633',1,'']]],
  ['packaging_4',['3. Packaging',['../contrib_release_checklist.html#autotoc_md394',1,'']]],
  ['packaging_20notes_5',['Packaging Notes',['../user_installation.html#autotoc_md640',1,'']]],
  ['packetframer_6',['packetframer',['../classunilink_1_1framer_1_1PacketFramer.html',1,'unilink::framer::PacketFramer'],['../classunilink_1_1framer_1_1PacketFramer.html#af95988deeb0863d7df1fb2bcda01763d',1,'unilink::framer::PacketFramer::PacketFramer()']]],
  ['packets_7',['Problem: UDP with Reliable Strategy Still Drops Packets',['../user_troubleshooting.html#autotoc_md781',1,'']]],
  ['pair_8',['Manual Virtual Serial Pair',['../contrib_orin_nano_validation.html#autotoc_md381',1,'']]],
  ['parallel_9',['Run Tests in Parallel',['../contrib_testing.html#autotoc_md424',1,'']]],
  ['parallel_20builds_10',['Parallel Builds',['../contrib_build.html#autotoc_md309',1,'']]],
  ['parallel_20initialization_11',['3. Parallel Initialization',['../user_tutorial_async.html#autotoc_md899',1,'']]],
  ['pass_20criteria_12',['Pass Criteria',['../contrib_orin_nano_validation.html#autotoc_md384',1,'']]],
  ['path_13',['path',['../user_troubleshooting.html#autotoc_md758',1,'2. Add Include Path'],['../user_troubleshooting.html#autotoc_md763',1,'2. Check Library Path'],['../user_troubleshooting.html#autotoc_md769',1,'Manual Boost Path'],['../tutorial_04.html#autotoc_md859',1,'Step 1: Choose A Device Path']]],
  ['paths_14',['Device Paths',['../user_api_guide.html#autotoc_md531',1,'']]],
  ['pattern_15',['pattern',['../contrib_arch.html#autotoc_md117',1,'1. Builder Pattern'],['../contrib_arch.html#autotoc_md119',1,'3. Observer Pattern'],['../contrib_arch.html#autotoc_md120',1,'4. Singleton Pattern'],['../contrib_arch.html#autotoc_md122',1,'6. Template Method Pattern'],['../user_api_guide.html#autotoc_md523',1,'Echo Server Pattern'],['../user_tutorial_async.html#autotoc_md897',1,'Safe Capture Pattern'],['../user_tutorial_async.html#autotoc_md894',1,'The Async Pattern']]],
  ['pattern_201_3a_20auto_20reconnection_16',['Pattern 1: Auto-Reconnection',['../user_quickstart.html#autotoc_md673',1,'']]],
  ['pattern_202_3a_20error_20handling_17',['Pattern 2: Error Handling',['../user_quickstart.html#autotoc_md674',1,'']]],
  ['pattern_203_3a_20connection_20limits_20optional_18',['Pattern 3: Connection Limits (optional)',['../user_quickstart.html#autotoc_md675',1,'']]],
  ['patterns_19',['patterns',['../user_tutorial_async.html',1,'Asynchronous Programming Patterns'],['../user_quickstart.html#autotoc_md672',1,'Common Patterns'],['../contrib_arch.html#autotoc_md116',1,'Design Patterns']]],
  ['patterns_20used_20in_20this_20tutorial_20',['API Patterns Used In This Tutorial',['../tutorial_01.html#autotoc_md822',1,'']]],
  ['pause_20sending_21',['Strategy 1: Pause Sending',['../contrib_arch_runtime.html#autotoc_md215',1,'']]],
  ['performance_22',['Performance',['../contrib_arch_memory.html#autotoc_md87',1,'']]],
  ['performance_20considerations_23',['performance considerations',['../contrib_arch.html#autotoc_md150',1,'Performance Considerations'],['../contrib_arch_runtime.html#autotoc_md238',1,'Performance Considerations']]],
  ['performance_20guide_24',['Performance Guide',['../user_performance.html',1,'user_index']]],
  ['performance_20impact_25',['Performance Impact',['../contrib_arch_memory.html#autotoc_md61',1,'']]],
  ['performance_20issues_26',['Performance Issues',['../user_troubleshooting.html#autotoc_md783',1,'']]],
  ['performance_20monitoring_27',['3. Performance Monitoring',['../contrib_arch_memory.html#autotoc_md48',1,'']]],
  ['performance_20regression_20testing_28',['Performance Regression Testing',['../contrib_testing.html#autotoc_md476',1,'']]],
  ['performance_20tips_29',['performance tips',['../contrib_build.html#autotoc_md308',1,'Build Performance Tips'],['../user_api_guide.html#autotoc_md584',1,'Performance Tips']]],
  ['permission_20denied_20during_20install_30',['Problem: Permission Denied During Install',['../contrib_build.html#autotoc_md327',1,'']]],
  ['phase_201_3a_20design_31',['Phase 1: Design',['../contrib_design_send_result.html#autotoc_md350',1,'']]],
  ['phase_202_3a_20experimental_20api_32',['Phase 2: Experimental API',['../contrib_design_send_result.html#autotoc_md351',1,'']]],
  ['phase_203_3a_20official_200_208_20api_33',['Phase 3: Official 0.8 API',['../contrib_design_send_result.html#autotoc_md352',1,'']]],
  ['phase_204_3a_20long_20term_34',['Phase 4: Long-Term',['../contrib_design_send_result.html#autotoc_md353',1,'']]],
  ['physical_20loopback_35',['Physical Loopback',['../contrib_orin_nano_validation.html#autotoc_md382',1,'']]],
  ['plain_20cmake_20with_20existing_20dependencies_36',['Option B: Plain CMake with existing dependencies',['../user_installation.html#autotoc_md630',1,'']]],
  ['plain_20cmake_20with_20vcpkg_20toolchain_37',['Option C: Plain CMake with vcpkg toolchain',['../user_installation.html#autotoc_md631',1,'']]],
  ['plan_38',['Migration Plan',['../contrib_design_send_result.html#autotoc_md349',1,'']]],
  ['planned_20design_20only_20apis_39',['Planned / Design-Only APIs',['../user_transport_matrix.html#autotoc_md731',1,'']]],
  ['platform_40',['Recommended Platform',['../user_requirements.html#autotoc_md687',1,'']]],
  ['platform_20notes_41',['Platform Notes',['../user_transport_matrix.html#autotoc_md730',1,'']]],
  ['platform_20specific_20builds_42',['Platform-Specific Builds',['../contrib_build.html#autotoc_md294',1,'']]],
  ['platform_20specific_20notes_43',['Platform-Specific Notes',['../user_requirements.html#autotoc_md702',1,'']]],
  ['platforminfo_44',['PlatformInfo',['../classunilink_1_1base_1_1PlatformInfo.html',1,'unilink::base']]],
  ['platforms_45',['Supported Platforms',['../user_requirements.html#autotoc_md688',1,'']]],
  ['pointers_46',['1. Smart Pointers',['../contrib_arch.html#autotoc_md135',1,'']]],
  ['points_47',['points',['../contrib_arch.html#autotoc_md155',1,'Extension Points'],['../contrib_arch_runtime.html#autotoc_md176',1,'Key Points']]],
  ['policies_48',['UDP-specific test policies',['../contrib_testing.html#autotoc_md426',1,'']]],
  ['policy_49',['policy',['../contrib_arch_channel.html#autotoc_md6',1,'4. Backpressure Policy'],['../user_api_stability.html',1,'API Stability Policy'],['../user_api_guide.html#autotoc_md495',1,'Callback Registration Policy'],['../user_api_stability.html#autotoc_md610',1,'Deprecation Policy'],['../user_api_stability.html#autotoc_md612',1,'Recommended Include Policy']]],
  ['policy_20state_20machine_50',['Reconnection Policy &amp; State Machine',['../contrib_arch_runtime.html#autotoc_md187',1,'']]],
  ['pool_51',['2. Memory Pool',['../contrib_arch.html#autotoc_md136',1,'']]],
  ['pooledbuffer_52',['PooledBuffer',['../classunilink_1_1memory_1_1PooledBuffer.html',1,'unilink::memory']]],
  ['pooling_53',['3. Memory Pooling',['../contrib_arch.html#autotoc_md153',1,'']]],
  ['poolstats_54',['PoolStats',['../structunilink_1_1memory_1_1MemoryPool_1_1PoolStats.html',1,'unilink::memory::MemoryPool']]],
  ['port_55',['port',['../user_troubleshooting.html#autotoc_md752',1,'2. Use Different Port'],['../user_troubleshooting.html#autotoc_md738',1,'2. Wrong Host/Port']]],
  ['port_20already_20in_20use_56',['port already in use',['../user_quickstart.html#autotoc_md681',1,'Port already in use?'],['../user_troubleshooting.html#autotoc_md750',1,'Problem: Port Already in Use']]],
  ['port_20binding_20failures_57',['Port-Binding Failures',['../contrib_orin_nano_validation.html#autotoc_md389',1,'']]],
  ['port_20conflicts_58',['Port Conflicts',['../contrib_testing.html#autotoc_md472',1,'']]],
  ['port_20retry_59',['port retry',['../user_troubleshooting.html#autotoc_md753',1,'3. Enable Port Retry'],['../user_api_guide.html#autotoc_md522',1,'Port Retry']]],
  ['post_20release_20checks_60',['7. Post-Release Checks',['../contrib_release_checklist.html#autotoc_md398',1,'']]],
  ['practical_20notes_61',['Practical Notes',['../tutorial_05.html#autotoc_md886',1,'']]],
  ['practices_62',['practices',['../contrib_arch_runtime.html#autotoc_md226',1,'1. Threading Best Practices'],['../contrib_arch_runtime.html#autotoc_md230',1,'2. Reconnection Best Practices'],['../contrib_arch_runtime.html#autotoc_md234',1,'3. Backpressure Best Practices'],['../contrib_arch_runtime.html#autotoc_md225',1,'Best Practices'],['../contrib_arch_memory.html#autotoc_md63',1,'Best Practices'],['../user_api_guide.html#autotoc_md577',1,'Best Practices'],['../contrib_arch_runtime.html#autotoc_md202',1,'Reconnection Best Practices']]],
  ['prefix_63',['prefix',['../contrib_build.html#autotoc_md331',1,'Custom Installation Prefix'],['../user_installation.html#autotoc_md635',1,'Step 2: Choose an install prefix']]],
  ['prerequisites_64',['prerequisites',['../contrib_build.html#autotoc_md298',1,'Prerequisites'],['../user_installation.html#autotoc_md623',1,'Prerequisites'],['../contrib_orin_nano_validation.html#autotoc_md373',1,'Prerequisites']]],
  ['prevents_20common_20vulnerabilities_65',['Prevents Common Vulnerabilities',['../contrib_arch_memory.html#autotoc_md85',1,'']]],
  ['principles_66',['2. Core Principles',['../contrib_arch_channel.html#autotoc_md4',1,'']]],
  ['problem_20statement_67',['Problem Statement',['../contrib_design_send_result.html#autotoc_md336',1,'']]],
  ['problem_3a_20boost_20not_20found_68',['problem: boost not found',['../user_requirements.html#autotoc_md716',1,'Problem: Boost Not Found'],['../user_troubleshooting.html#autotoc_md765',1,'Problem: Boost Not Found']]],
  ['problem_3a_20callbacks_20not_20being_20called_69',['Problem: Callbacks Not Being Called',['../user_troubleshooting.html#autotoc_md776',1,'']]],
  ['problem_3a_20cmake_20can_20t_20find_20boost_70',['Problem: CMake Can&apos;t Find Boost',['../contrib_build.html#autotoc_md324',1,'']]],
  ['problem_3a_20cmake_20too_20old_71',['Problem: CMake Too Old',['../user_requirements.html#autotoc_md717',1,'']]],
  ['problem_3a_20compiler_20not_20found_72',['Problem: Compiler Not Found',['../contrib_build.html#autotoc_md325',1,'']]],
  ['problem_3a_20compiler_20too_20old_73',['Problem: Compiler Too Old',['../user_requirements.html#autotoc_md715',1,'']]],
  ['problem_3a_20connection_20drops_20randomly_74',['Problem: Connection Drops Randomly',['../user_troubleshooting.html#autotoc_md745',1,'']]],
  ['problem_3a_20connection_20refused_75',['Problem: Connection Refused',['../user_troubleshooting.html#autotoc_md736',1,'']]],
  ['problem_3a_20connection_20timeout_76',['Problem: Connection Timeout',['../user_troubleshooting.html#autotoc_md741',1,'']]],
  ['problem_3a_20high_20cpu_20usage_77',['Problem: High CPU Usage',['../user_troubleshooting.html#autotoc_md784',1,'']]],
  ['problem_3a_20high_20memory_20usage_78',['Problem: High Memory Usage',['../user_troubleshooting.html#autotoc_md789',1,'']]],
  ['problem_3a_20memory_20leak_20detected_79',['Problem: Memory Leak Detected',['../user_troubleshooting.html#autotoc_md799',1,'']]],
  ['problem_3a_20out_20of_20memory_20during_20build_80',['Problem: Out of Memory During Build',['../contrib_build.html#autotoc_md326',1,'']]],
  ['problem_3a_20permission_20denied_20during_20install_81',['Problem: Permission Denied During Install',['../contrib_build.html#autotoc_md327',1,'']]],
  ['problem_3a_20port_20already_20in_20use_82',['Problem: Port Already in Use',['../user_troubleshooting.html#autotoc_md750',1,'']]],
  ['problem_3a_20race_20condition_20data_20corruption_83',['Problem: Race Condition / Data Corruption',['../user_troubleshooting.html#autotoc_md802',1,'']]],
  ['problem_3a_20segmentation_20fault_84',['Problem: Segmentation Fault',['../user_troubleshooting.html#autotoc_md772',1,'']]],
  ['problem_3a_20slow_20data_20transfer_85',['Problem: Slow Data Transfer',['../user_troubleshooting.html#autotoc_md793',1,'']]],
  ['problem_3a_20udp_20with_20reliable_20strategy_20still_20drops_20packets_86',['Problem: UDP with Reliable Strategy Still Drops Packets',['../user_troubleshooting.html#autotoc_md781',1,'']]],
  ['problem_3a_20undefined_20reference_20to_20unilink_20symbols_87',['Problem: Undefined Reference to unilink Symbols',['../user_troubleshooting.html#autotoc_md761',1,'']]],
  ['problem_3a_20unilink_20unilink_20hpp_20not_20found_88',['Problem: unilink/unilink.hpp Not Found',['../user_troubleshooting.html#autotoc_md756',1,'']]],
  ['process_89',['1. Kill Existing Process',['../user_troubleshooting.html#autotoc_md751',1,'']]],
  ['production_20build_90',['Example 1: Minimal Production Build',['../contrib_build.html#autotoc_md284',1,'']]],
  ['programming_20patterns_91',['Asynchronous Programming Patterns',['../user_tutorial_async.html',1,'']]],
  ['programs_92',['programs',['../tutorial_05.html#autotoc_md880',1,'Step 3: Build The Two Programs'],['../tutorial_05.html#autotoc_md882',1,'Step 4: Run Both Programs']]],
  ['programs_20for_20more_93',['Use The Full Example Programs For More',['../tutorial_02.html#autotoc_md839',1,'']]],
  ['programs_20instead_94',['When To Use The Example Programs Instead',['../tutorial_04.html#autotoc_md869',1,'']]],
  ['project_95',['project',['../user_installation.html#autotoc_md627',1,'Step 2: Use in your project'],['../user_installation.html#autotoc_md636',1,'Step 3: Use in your project'],['../user_installation.html#autotoc_md632',1,'Use in your project']]],
  ['propagation_20flow_96',['Error Propagation Flow',['../contrib_arch.html#autotoc_md141',1,'']]],
  ['proposed_20api_97',['Proposed API',['../contrib_design_send_result.html#autotoc_md340',1,'']]],
  ['protect_20shared_20state_98',['1. Protect Shared State',['../user_troubleshooting.html#autotoc_md803',1,'']]],
  ['protocol_99',['2. Use Binary Protocol',['../user_troubleshooting.html#autotoc_md795',1,'']]],
  ['public_20surface_100',['Stable Public Surface',['../user_api_stability.html#autotoc_md604',1,'']]],
  ['push_5fbytes_101',['push_bytes',['../classunilink_1_1framer_1_1PacketFramer.html#ae0de7a72e4794e1df90a30eb73289993',1,'unilink::framer::PacketFramer::push_bytes()'],['../classunilink_1_1framer_1_1LineFramer.html#a5d2f38f248590d01685c302819a5c717',1,'unilink::framer::LineFramer::push_bytes()'],['../classunilink_1_1framer_1_1IFramer.html#ad26b5b0975a33c2f95f4a31b7d61a809',1,'unilink::framer::IFramer::push_bytes()']]],
  ['python_20binding_20scope_102',['Python Binding Scope',['../contrib_impl_status.html#autotoc_md357',1,'']]],
  ['python_20bindings_103',['python bindings',['../user_api_stability.html#autotoc_md611',1,'Python Bindings'],['../user_python_bindings.html',1,'Python Bindings']]]
];
