var searchData=
[
  ['ubuntu_2020_2004_20build_0',['Ubuntu 20.04 Build',['../contrib_build.html#autotoc_md297',1,'']]],
  ['ubuntu_2020_2004_20lts_1',['Ubuntu 20.04 LTS',['../user_requirements.html#autotoc_md705',1,'']]],
  ['ubuntu_2020_2004_20support_2',['Ubuntu 20.04 Support',['../contrib_testing.html#autotoc_md453',1,'']]],
  ['ubuntu_2022_2004_20lts_3',['Ubuntu 22.04 LTS',['../user_requirements.html#autotoc_md703',1,'']]],
  ['ubuntu_2022_2004_20recommended_4',['Ubuntu 22.04 (Recommended)',['../contrib_build.html#autotoc_md295',1,'']]],
  ['ubuntu_20arm64_20jetson_20orin_20nano_5',['Ubuntu ARM64 / Jetson Orin Nano',['../user_requirements.html#autotoc_md704',1,'']]],
  ['udp_6',['What Is Different About UDP',['../tutorial_05.html#autotoc_md884',1,'']]],
  ['udp_20communication_7',['udp communication',['../tutorial_05.html',1,'UDP Communication'],['../user_api_guide.html#autotoc_md536',1,'UDP Communication']]],
  ['udp_20receiver_20server_8',['UDP Receiver (Server)',['../user_api_guide.html#autotoc_md538',1,'']]],
  ['udp_20sender_20client_9',['UDP Sender (Client)',['../user_api_guide.html#autotoc_md539',1,'']]],
  ['udp_20server_20receive_20only_20listener_10',['UDP Server (Receive-only listener)',['../user_api_guide.html#autotoc_md547',1,'']]],
  ['udp_20specific_20test_20policies_11',['UDP-specific test policies',['../contrib_testing.html#autotoc_md426',1,'']]],
  ['udp_20with_20reliable_20strategy_20still_20drops_20packets_12',['Problem: UDP with Reliable Strategy Still Drops Packets',['../user_troubleshooting.html#autotoc_md781',1,'']]],
  ['udp_5fclient_13',['udp_client',['../classunilink_1_1builder_1_1UnifiedBuilder.html#a3bd3d5f8eae5b4010dd87f7a5c529d4d',1,'unilink::builder::UnifiedBuilder']]],
  ['udp_5fserver_14',['udp_server',['../classunilink_1_1builder_1_1UnifiedBuilder.html#aee7dbfdf478ca4ced6f3a0caa6f41291',1,'unilink::builder::UnifiedBuilder']]],
  ['udpchannel_15',['UdpChannel',['../classunilink_1_1transport_1_1UdpChannel.html',1,'unilink::transport']]],
  ['udpclient_16',['udpclient',['../user_api_guide.html#autotoc_md542',1,'Builder Methods (UdpClient)'],['../user_api_guide.html#autotoc_md544',1,'Instance Methods (UdpClient)'],['../classunilink_1_1wrapper_1_1UdpClient.html',1,'unilink::wrapper::UdpClient']]],
  ['udpclientbuilder_17',['UdpClientBuilder',['../classunilink_1_1builder_1_1UdpClientBuilder.html',1,'unilink::builder']]],
  ['udpconfig_18',['UdpConfig',['../structunilink_1_1config_1_1UdpConfig.html',1,'unilink::config']]],
  ['udpserver_19',['udpserver',['../user_api_guide.html#autotoc_md543',1,'Builder Methods (UdpServer)'],['../classunilink_1_1wrapper_1_1UdpServer.html',1,'unilink::wrapper::UdpServer']]],
  ['udpserverbuilder_20',['UdpServerBuilder',['../classunilink_1_1builder_1_1UdpServerBuilder.html',1,'unilink::builder']]],
  ['uds_21',['Notes on UDS',['../user_api_guide.html#autotoc_md559',1,'']]],
  ['uds_20client_22',['uds client',['../user_api_guide.html#autotoc_md556',1,'Builder Methods (UDS Client)'],['../user_api_guide.html#autotoc_md557',1,'Instance Methods (UDS Client)'],['../tutorial_03.html#autotoc_md848',1,'Step 2: Create A UDS Client'],['../user_api_guide.html#autotoc_md552',1,'UDS Client']]],
  ['uds_20communication_23',['uds communication',['../user_api_guide.html#autotoc_md549',1,'UDS Communication'],['../tutorial_03.html',1,'UDS Communication']]],
  ['uds_20instead_20of_20tcp_24',['Why Use UDS Instead Of TCP',['../tutorial_03.html#autotoc_md850',1,'']]],
  ['uds_20server_25',['uds server',['../user_api_guide.html#autotoc_md555',1,'Builder Methods (UDS Server)'],['../user_api_guide.html#autotoc_md558',1,'Instance Methods (UDS Server)'],['../tutorial_03.html#autotoc_md846',1,'Step 1: Create A UDS Server'],['../user_api_guide.html#autotoc_md551',1,'UDS Server']]],
  ['udsacceptorinterface_26',['UdsAcceptorInterface',['../classunilink_1_1interface_1_1UdsAcceptorInterface.html',1,'unilink::interface']]],
  ['udsclient_27',['udsclient',['../classunilink_1_1transport_1_1UdsClient.html',1,'unilink::transport::UdsClient'],['../classunilink_1_1wrapper_1_1UdsClient.html',1,'unilink::wrapper::UdsClient']]],
  ['udsclientbuilder_28',['UdsClientBuilder',['../classunilink_1_1builder_1_1UdsClientBuilder.html',1,'unilink::builder']]],
  ['udsclientconfig_29',['UdsClientConfig',['../structunilink_1_1config_1_1UdsClientConfig.html',1,'unilink::config']]],
  ['udsserver_30',['udsserver',['../classunilink_1_1transport_1_1UdsServer.html',1,'unilink::transport::UdsServer'],['../classunilink_1_1wrapper_1_1UdsServer.html',1,'unilink::wrapper::UdsServer']]],
  ['udsserverbuilder_31',['UdsServerBuilder',['../classunilink_1_1builder_1_1UdsServerBuilder.html',1,'unilink::builder']]],
  ['udsserverconfig_32',['UdsServerConfig',['../structunilink_1_1config_1_1UdsServerConfig.html',1,'unilink::config']]],
  ['udsserversession_33',['UdsServerSession',['../classunilink_1_1transport_1_1UdsServerSession.html',1,'unilink::transport']]],
  ['udssocketinterface_34',['UdsSocketInterface',['../classunilink_1_1interface_1_1UdsSocketInterface.html',1,'unilink::interface']]],
  ['undefined_20reference_20to_20unilink_20symbols_35',['Problem: Undefined Reference to unilink Symbols',['../user_troubleshooting.html#autotoc_md761',1,'']]],
  ['understand_20the_20current_20server_20api_36',['Step 3: Understand The Current Server API',['../tutorial_02.html#autotoc_md835',1,'']]],
  ['unifiedbuilder_37',['UnifiedBuilder',['../classunilink_1_1builder_1_1UnifiedBuilder.html',1,'unilink::builder']]],
  ['unilink_38',['unilink',['../user_troubleshooting.html#autotoc_md757',1,'1. Install unilink'],['../user_requirements.html#autotoc_md699',1,'For Applications Using unilink'],['../tutorial_01.html',1,'Getting Started with Unilink']]],
  ['unilink_20api_20guide_39',['Unilink API Guide',['../user_api_guide.html',1,'user_index']]],
  ['unilink_20docs_40',['unilink-docs',['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2README.html',1,'']]],
  ['unilink_20documentation_41',['Unilink Documentation',['../index.html',1,'']]],
  ['unilink_20library_42',['1. Link unilink Library',['../user_troubleshooting.html#autotoc_md762',1,'']]],
  ['unilink_20logo_20assets_43',['unilink Logo Assets',['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2docs_2assets_2logo_2README.html',1,'']]],
  ['unilink_20quick_20start_20guide_44',['Unilink Quick Start Guide',['../user_quickstart.html',1,'user_index']]],
  ['unilink_20symbols_45',['Problem: Undefined Reference to unilink Symbols',['../user_troubleshooting.html#autotoc_md761',1,'']]],
  ['unilink_20system_20architecture_46',['Unilink System Architecture',['../contrib_arch.html',1,'contrib_index']]],
  ['unilink_20unilink_20hpp_20not_20found_47',['Problem: unilink/unilink.hpp Not Found',['../user_troubleshooting.html#autotoc_md756',1,'']]],
  ['unilink_3a_3abuilder_3a_3abatchdatahandler_48',['BatchDataHandler',['../conceptunilink_1_1builder_1_1BatchDataHandler.html',1,'unilink::builder']]],
  ['unilink_3a_3abuilder_3a_3aconnectionhandler_49',['ConnectionHandler',['../conceptunilink_1_1builder_1_1ConnectionHandler.html',1,'unilink::builder']]],
  ['unilink_3a_3abuilder_3a_3adatahandler_50',['DataHandler',['../conceptunilink_1_1builder_1_1DataHandler.html',1,'unilink::builder']]],
  ['unilink_3a_3abuilder_3a_3aerrorhandler_51',['ErrorHandler',['../conceptunilink_1_1builder_1_1ErrorHandler.html',1,'unilink::builder']]],
  ['unilink_3a_3adiagnostics_3a_3aerror_5freporting_52',['error_reporting',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html',1,'unilink::diagnostics']]],
  ['unilink_3a_3amemory_3a_3amemory_5fvalidator_53',['memory_validator',['../namespaceunilink_1_1memory_1_1memory__validator.html',1,'unilink::memory']]],
  ['unilink_3a_3amemory_3a_3asafe_5fbuffer_5ffactory_54',['safe_buffer_factory',['../namespaceunilink_1_1memory_1_1safe__buffer__factory.html',1,'unilink::memory']]],
  ['unilinkexception_55',['UnilinkException',['../classunilink_1_1diagnostics_1_1UnilinkException.html',1,'unilink::diagnostics']]],
  ['uninstall_56',['Uninstall',['../contrib_build.html#autotoc_md316',1,'']]],
  ['unit_20tests_57',['unit tests',['../contrib_build.html#autotoc_md319',1,'Run Unit Tests'],['../contrib_arch_memory.html#autotoc_md90',1,'Unit Tests']]],
  ['unmanaged_20external_20contexts_20have_20different_20ownership_20rules_58',['5. Managed and unmanaged external contexts have different ownership rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'']]],
  ['unreachable_59',['1. Network Unreachable',['../user_troubleshooting.html#autotoc_md742',1,'']]],
  ['usage_60',['usage',['../user_api_guide.html#autotoc_md526',1,'Basic Usage'],['../user_api_guide.html#autotoc_md567',1,'Basic Usage'],['../user_api_guide.html#autotoc_md505',1,'Basic Usage'],['../user_api_guide.html#autotoc_md515',1,'Basic Usage'],['../user_api_guide.html#autotoc_md537',1,'Basic Usage'],['../user_api_guide.html#autotoc_md550',1,'Basic Usage'],['../user_api_guide.html#autotoc_md596',1,'C++ Usage'],['../user_troubleshooting.html#autotoc_md784',1,'Problem: High CPU Usage'],['../user_troubleshooting.html#autotoc_md789',1,'Problem: High Memory Usage'],['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2docs_2assets_2logo_2README.html#autotoc_md2',1,'Usage']]],
  ['use_61',['use',['../user_quickstart.html#autotoc_md681',1,'Port already in use?'],['../user_troubleshooting.html#autotoc_md750',1,'Problem: Port Already in Use']]],
  ['use_20as_20subdirectory_62',['3. Use as Subdirectory',['../user_troubleshooting.html#autotoc_md759',1,'']]],
  ['use_20async_20vs_20sync_63',['4. When to Use Async vs Sync',['../user_tutorial_async.html#autotoc_md901',1,'']]],
  ['use_20binary_20protocol_64',['2. Use Binary Protocol',['../user_troubleshooting.html#autotoc_md795',1,'']]],
  ['use_20different_20port_65',['2. Use Different Port',['../user_troubleshooting.html#autotoc_md752',1,'']]],
  ['use_20each_66',['When to use each',['../user_api_guide.html#autotoc_md595',1,'']]],
  ['use_20explicit_20lifecycle_20control_67',['2. Use Explicit Lifecycle Control',['../user_api_guide.html#autotoc_md579',1,'']]],
  ['use_20gdb_20for_20debugging_68',['Use GDB for Debugging',['../user_troubleshooting.html#autotoc_md807',1,'']]],
  ['use_20in_20cmake_69',['Step 2: Use in CMake',['../user_installation.html#autotoc_md639',1,'']]],
  ['use_20in_20your_20project_70',['use in your project',['../user_installation.html#autotoc_md627',1,'Step 2: Use in your project'],['../user_installation.html#autotoc_md636',1,'Step 3: Use in your project'],['../user_installation.html#autotoc_md632',1,'Use in your project']]],
  ['use_20independent_20context_20for_20testing_20only_71',['1. Use Independent Context for Testing Only',['../user_api_guide.html#autotoc_md585',1,'']]],
  ['use_20member_20functions_20for_20oop_20design_72',['5. Use Member Functions for OOP Design',['../user_api_guide.html#autotoc_md582',1,'']]],
  ['use_20the_20example_20programs_20instead_73',['When To Use The Example Programs Instead',['../tutorial_04.html#autotoc_md869',1,'']]],
  ['use_20the_20full_20example_20if_20you_20want_20more_74',['Use The Full Example If You Want More',['../tutorial_01.html#autotoc_md824',1,'']]],
  ['use_20the_20full_20example_20programs_20for_20more_75',['Use The Full Example Programs For More',['../tutorial_02.html#autotoc_md839',1,'']]],
  ['use_20the_20full_20examples_20for_20repeated_20testing_76',['Use The Full Examples For Repeated Testing',['../tutorial_05.html#autotoc_md888',1,'']]],
  ['use_20uds_20instead_20of_20tcp_77',['Why Use UDS Instead Of TCP',['../tutorial_03.html#autotoc_md850',1,'']]],
  ['use_5fafter_5ffree_78',['use_after_free',['../namespaceunilink_1_1memory_1_1memory__validator.html#a369bd3ff4ed187a13d23ccf7c891b079',1,'unilink::memory::memory_validator']]],
  ['use_5fline_5fframer_79',['use_line_framer',['../classunilink_1_1builder_1_1BuilderInterface.html#afa3cf1eea9a21dbb7d6734f86b822859',1,'unilink::builder::BuilderInterface']]],
  ['use_5fpacket_5fframer_80',['use_packet_framer',['../classunilink_1_1builder_1_1BuilderInterface.html#a0a6746e287da46523fef3ee23d79168a',1,'unilink::builder::BuilderInterface']]],
  ['used_20in_20this_20tutorial_81',['API Patterns Used In This Tutorial',['../tutorial_01.html#autotoc_md822',1,'']]],
  ['useful_20focused_20runs_82',['Useful Focused Runs',['../contrib_test_structure.html#autotoc_md405',1,'']]],
  ['user_20docs_83',['Quick Links (User Docs)',['../contrib_index.html#autotoc_md367',1,'']]],
  ['user_20guide_84',['User Guide',['../user_index.html',1,'']]],
  ['users_85',['📖 For Library Users',['../index.html#autotoc_md484',1,'']]],
  ['uses_20the_20latest_20callback_86',['6. Handler replacement uses the latest callback',['../contrib_arch_wrapper.html#autotoc_md253',1,'']]],
  ['using_20the_20installed_20package_87',['Using the Installed Package',['../contrib_build.html#autotoc_md330',1,'']]],
  ['using_20unilink_88',['For Applications Using unilink',['../user_requirements.html#autotoc_md699',1,'']]],
  ['utilities_89',['4. Common Utilities',['../contrib_arch.html#autotoc_md114',1,'']]],
  ['utilities_20layer_90',['4. Common Utilities Layer',['../contrib_arch.html#autotoc_md108',1,'']]]
];
