var searchData=
[
  ['c_20api_20surface_0',['C++ API Surface',['../contrib_impl_status.html#autotoc_md356',1,'']]],
  ['c_20standard_1',['C++ Standard',['../user_requirements.html#autotoc_md696',1,'']]],
  ['c_20tests_2',['Run C++ Tests',['../contrib_orin_nano_validation.html#autotoc_md377',1,'']]],
  ['c_20usage_3',['C++ Usage',['../user_api_guide.html#autotoc_md596',1,'']]],
  ['c_3a_20plain_20cmake_20with_20vcpkg_20toolchain_4',['Option C: Plain CMake with vcpkg toolchain',['../user_installation.html#autotoc_md631',1,'']]],
  ['callback_5',['callback',['../user_troubleshooting.html#autotoc_md785',1,'1. Busy Loop in Callback'],['../contrib_arch_wrapper.html#autotoc_md253',1,'6. Handler replacement uses the latest callback']]],
  ['callback_20contract_6',['Callback Contract',['../contrib_arch_wrapper.html#autotoc_md252',1,'']]],
  ['callback_20execution_7',['Threading Model &amp; Callback Execution',['../contrib_arch_runtime.html#autotoc_md173',1,'']]],
  ['callback_20execution_20context_8',['✅ Callback Execution Context',['../contrib_arch_runtime.html#autotoc_md179',1,'']]],
  ['callback_20not_20registered_9',['1. Receive Callback Not Registered',['../user_troubleshooting.html#autotoc_md777',1,'']]],
  ['callback_20registration_20policy_10',['Callback Registration Policy',['../user_api_guide.html#autotoc_md495',1,'']]],
  ['callback_5fsink_11',['callback_sink',['../classunilink_1_1diagnostics_1_1callback__sink.html',1,'unilink::diagnostics']]],
  ['callbacks_12',['callbacks',['../contrib_arch_runtime.html#autotoc_md181',1,'⚠️ Never Block in Callbacks'],['../contrib_arch.html#autotoc_md128',1,'2. Callbacks'],['../user_tutorial_async.html#autotoc_md896',1,'2. Shared Ownership in Callbacks'],['../user_performance.html#autotoc_md649',1,'3. Non-Blocking Callbacks'],['../contrib_arch_runtime.html#autotoc_md198',1,'State Callbacks']]],
  ['callbacks_20after_20stop_13',['3. Stop Semantics: No Callbacks After Stop()',['../contrib_arch_channel.html#autotoc_md5',1,'']]],
  ['callbacks_20after_20tt_20stop_20tt_20returns_14',['7. No wrapper callbacks after &lt;tt&gt;stop()&lt;/tt&gt; returns',['../contrib_arch_wrapper.html#autotoc_md254',1,'']]],
  ['callbacks_20not_20being_20called_15',['Problem: Callbacks Not Being Called',['../user_troubleshooting.html#autotoc_md776',1,'']]],
  ['called_16',['Problem: Callbacks Not Being Called',['../user_troubleshooting.html#autotoc_md776',1,'']]],
  ['camera_17',['2. High-Throughput Sensors (LiDAR/Camera)',['../user_performance.html#autotoc_md662',1,'']]],
  ['can_20be_20reused_18',['4. Externally supplied &lt;tt&gt;io_context&lt;/tt&gt; can be reused',['../contrib_arch_wrapper.html#autotoc_md250',1,'']]],
  ['can_20t_20connect_20to_20server_19',['Can&apos;t connect to server?',['../user_quickstart.html#autotoc_md680',1,'']]],
  ['can_20t_20find_20boost_20',['Problem: CMake Can&apos;t Find Boost',['../contrib_build.html#autotoc_md324',1,'']]],
  ['capacity_21',['2. Reserve Vector Capacity',['../user_performance.html#autotoc_md653',1,'']]],
  ['capture_22',['With Lambda Capture',['../user_api_guide.html#autotoc_md512',1,'']]],
  ['capture_20pattern_23',['Safe Capture Pattern',['../user_tutorial_async.html#autotoc_md897',1,'']]],
  ['categories_24',['categories',['../contrib_arch.html#autotoc_md142',1,'Error Categories'],['../contrib_testing.html#autotoc_md420',1,'Run Specific Test Categories'],['../contrib_testing.html#autotoc_md427',1,'Test Categories']]],
  ['category_25',['Run By Broad Category',['../contrib_test_structure.html#autotoc_md404',1,'']]],
  ['category_5fstring_26',['category_string',['../structunilink_1_1diagnostics_1_1ErrorInfo.html#a8a79a75dd8b77f302178afd3ff7ed665',1,'unilink::diagnostics::ErrorInfo']]],
  ['causes_27',['2. Common Causes',['../user_troubleshooting.html#autotoc_md774',1,'']]],
  ['ccache_20for_20faster_20rebuilds_28',['Ccache for Faster Rebuilds',['../contrib_build.html#autotoc_md310',1,'']]],
  ['cd_20build_20matrix_29',['CI/CD Build Matrix',['../contrib_testing.html#autotoc_md451',1,'']]],
  ['cd_20integration_30',['CI/CD Integration',['../contrib_test_structure.html#autotoc_md408',1,'']]],
  ['cd_20results_31',['View CI/CD Results',['../contrib_testing.html#autotoc_md455',1,'']]],
  ['channel_32',['Channel',['../classunilink_1_1interface_1_1Channel.html',1,'unilink::interface']]],
  ['channel_20contract_33',['Transport Channel Contract',['../contrib_arch_channel.html',1,'contrib_arch']]],
  ['channelfactory_34',['ChannelFactory',['../classunilink_1_1factory_1_1ChannelFactory.html',1,'unilink::factory']]],
  ['channelinterface_35',['ChannelInterface',['../classunilink_1_1wrapper_1_1ChannelInterface.html',1,'unilink::wrapper']]],
  ['check_20boost_20version_36',['Check Boost Version',['../user_requirements.html#autotoc_md711',1,'']]],
  ['check_20cmake_20version_37',['Check CMake Version',['../user_requirements.html#autotoc_md710',1,'']]],
  ['check_20compiler_20version_38',['Check Compiler Version',['../user_requirements.html#autotoc_md709',1,'']]],
  ['check_20library_20path_39',['2. Check Library Path',['../user_troubleshooting.html#autotoc_md763',1,'']]],
  ['check_20library_20symbols_40',['Check Library Symbols',['../contrib_build.html#autotoc_md321',1,'']]],
  ['check_5fbuffer_5fbounds_41',['check_buffer_bounds',['../namespaceunilink_1_1memory_1_1memory__validator.html#a60d61b8895e986a0bee5cafc38f60704',1,'unilink::memory::memory_validator']]],
  ['checklist_42',['Release Checklist',['../contrib_release_checklist.html',1,'']]],
  ['checks_43',['checks',['../contrib_release_checklist.html#autotoc_md397',1,'6. Compatibility Checks'],['../contrib_release_checklist.html#autotoc_md398',1,'7. Post-Release Checks']]],
  ['choose_20a_20device_20path_44',['Step 1: Choose A Device Path',['../tutorial_04.html#autotoc_md859',1,'']]],
  ['choose_20an_20install_20prefix_45',['Step 2: Choose an install prefix',['../user_installation.html#autotoc_md635',1,'']]],
  ['choose_20appropriate_20retry_20interval_46',['1. Choose Appropriate Retry Interval',['../contrib_arch_runtime.html#autotoc_md203',1,'']]],
  ['choosing_20a_20strategy_47',['1. Choosing a Strategy',['../user_performance.html#autotoc_md660',1,'']]],
  ['ci_20cd_20build_20matrix_48',['CI/CD Build Matrix',['../contrib_testing.html#autotoc_md451',1,'']]],
  ['ci_20cd_20integration_49',['CI/CD Integration',['../contrib_test_structure.html#autotoc_md408',1,'']]],
  ['ci_20cd_20results_50',['View CI/CD Results',['../contrib_testing.html#autotoc_md455',1,'']]],
  ['clear_5fcallbacks_51',['clear_callbacks',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#aed798efec33785cec8e38068013f673a',1,'unilink::diagnostics::ErrorHandler']]],
  ['client_52',['client',['../user_api_guide.html#autotoc_md556',1,'Builder Methods (UDS Client)'],['../user_api_guide.html#autotoc_md557',1,'Instance Methods (UDS Client)'],['../tutorial_01.html#autotoc_md816',1,'Step 1: Create The Client'],['../tutorial_03.html#autotoc_md848',1,'Step 2: Create A UDS Client'],['../user_api_guide.html#autotoc_md504',1,'TCP Client'],['../user_api_guide.html#autotoc_md539',1,'UDP Sender (Client)'],['../user_api_guide.html#autotoc_md552',1,'UDS Client'],['../user_quickstart.html#autotoc_md666',1,'Your First TCP Client']]],
  ['client_20limits_53',['Client Limits',['../tutorial_02.html#autotoc_md837',1,'']]],
  ['client_20mode_54',['Single Client Mode',['../user_api_guide.html#autotoc_md521',1,'']]],
  ['client_20not_20started_55',['2. Client Not Started',['../user_troubleshooting.html#autotoc_md778',1,'']]],
  ['client_5fid_56',['client_id',['../classunilink_1_1wrapper_1_1ErrorContext.html#a4c2b15d54b7bd62ba38a81abb1dc6505',1,'unilink::wrapper::ErrorContext::client_id()'],['../classunilink_1_1wrapper_1_1MessageContext.html#a5437876db064533f5885d28a50db8972',1,'unilink::wrapper::MessageContext::client_id()'],['../classunilink_1_1wrapper_1_1ConnectionContext.html#a9c487d4ec5f33ff9cd966427453588c7',1,'unilink::wrapper::ConnectionContext::client_id()']]],
  ['client_5finfo_57',['client_info',['../classunilink_1_1wrapper_1_1MessageContext.html#afebe58ba82f38e3b55fa2da21660fccf',1,'unilink::wrapper::MessageContext::client_info()'],['../classunilink_1_1wrapper_1_1ConnectionContext.html#acfe7e93440fd212929ae8009f64a4024',1,'unilink::wrapper::ConnectionContext::client_info()']]],
  ['closing_20connection_58',['2. Server Closing Connection',['../user_troubleshooting.html#autotoc_md747',1,'']]],
  ['cmake_59',['cmake',['../tutorial_01.html#autotoc_md818',1,'Step 2: Build With CMake'],['../user_installation.html#autotoc_md639',1,'Step 2: Use in CMake']]],
  ['cmake_20can_20t_20find_20boost_60',['Problem: CMake Can&apos;t Find Boost',['../contrib_build.html#autotoc_md324',1,'']]],
  ['cmake_20package_20integration_61',['CMake Package Integration',['../contrib_build.html#autotoc_md329',1,'']]],
  ['cmake_20too_20old_62',['Problem: CMake Too Old',['../user_requirements.html#autotoc_md717',1,'']]],
  ['cmake_20version_63',['Check CMake Version',['../user_requirements.html#autotoc_md710',1,'']]],
  ['cmake_20with_20existing_20dependencies_64',['Option B: Plain CMake with existing dependencies',['../user_installation.html#autotoc_md630',1,'']]],
  ['cmake_20with_20vcpkg_20toolchain_65',['Option C: Plain CMake with vcpkg toolchain',['../user_installation.html#autotoc_md631',1,'']]],
  ['code_66',['code',['../classunilink_1_1wrapper_1_1ErrorContext.html#a75baa0901a7b5c261e5f0f5615a13059',1,'unilink::wrapper::ErrorContext']]],
  ['code_20coverage_67',['Code Coverage',['../contrib_testing.html#autotoc_md478',1,'']]],
  ['common_20adjustments_68',['Common Adjustments',['../tutorial_04.html#autotoc_md867',1,'']]],
  ['common_20causes_69',['2. Common Causes',['../user_troubleshooting.html#autotoc_md774',1,'']]],
  ['common_20methods_20all_20builders_70',['Common Methods (All Builders)',['../user_api_guide.html#autotoc_md494',1,'']]],
  ['common_20patterns_71',['Common Patterns',['../user_quickstart.html#autotoc_md672',1,'']]],
  ['common_20utilities_72',['4. Common Utilities',['../contrib_arch.html#autotoc_md114',1,'']]],
  ['common_20utilities_20layer_73',['4. Common Utilities Layer',['../contrib_arch.html#autotoc_md108',1,'']]],
  ['common_20vulnerabilities_74',['Prevents Common Vulnerabilities',['../contrib_arch_memory.html#autotoc_md85',1,'']]],
  ['communication_75',['communication',['../user_api_guide.html#autotoc_md533',1,'Arduino Communication'],['../user_api_guide.html#autotoc_md525',1,'Serial Communication'],['../tutorial_04.html',1,'Serial Communication'],['../user_api_guide.html#autotoc_md536',1,'UDP Communication'],['../tutorial_05.html',1,'UDP Communication'],['../tutorial_03.html',1,'UDS Communication'],['../user_api_guide.html#autotoc_md549',1,'UDS Communication']]],
  ['comparison_76',['Build Types Comparison',['../contrib_build.html#autotoc_md276',1,'']]],
  ['compatibility_77',['compatibility',['../user_api_stability.html#autotoc_md608',1,'ABI Compatibility'],['../contrib_design_send_result.html#autotoc_md347',1,'API Compatibility'],['../user_api_stability.html#autotoc_md607',1,'Source Compatibility']]],
  ['compatibility_20checks_78',['6. Compatibility Checks',['../contrib_release_checklist.html#autotoc_md397',1,'']]],
  ['compilation_20errors_79',['Compilation Errors',['../user_troubleshooting.html#autotoc_md755',1,'']]],
  ['compile_20time_20configuration_80',['Compile-Time Configuration',['../contrib_arch.html#autotoc_md147',1,'']]],
  ['compiler_81',['Example 5: Build with Specific Compiler',['../contrib_build.html#autotoc_md292',1,'']]],
  ['compiler_20not_20found_82',['Problem: Compiler Not Found',['../contrib_build.html#autotoc_md325',1,'']]],
  ['compiler_20requirements_83',['Compiler Requirements',['../user_requirements.html#autotoc_md694',1,'']]],
  ['compiler_20too_20old_84',['Problem: Compiler Too Old',['../user_requirements.html#autotoc_md715',1,'']]],
  ['compiler_20version_85',['Check Compiler Version',['../user_requirements.html#autotoc_md709',1,'']]],
  ['compiler_20versions_86',['Minimum Compiler Versions',['../user_requirements.html#autotoc_md695',1,'']]],
  ['components_87',['components',['../contrib_arch.html#autotoc_md110',1,'Core Components'],['../contrib_build.html#autotoc_md332',1,'Package Components']]],
  ['concept_88',['Core Concept',['../user_api_guide.html#autotoc_md493',1,'']]],
  ['concurrency_20safety_20tests_89',['Concurrency Safety Tests',['../contrib_testing.html#autotoc_md432',1,'']]],
  ['concurrent_20runtime_20methods_90',['Concurrent Runtime Methods',['../contrib_arch_runtime.html#autotoc_md177',1,'']]],
  ['condition_20data_20corruption_91',['Problem: Race Condition / Data Corruption',['../user_troubleshooting.html#autotoc_md802',1,'']]],
  ['configfactory_92',['ConfigFactory',['../classunilink_1_1config_1_1ConfigFactory.html',1,'unilink::config']]],
  ['configitem_93',['ConfigItem',['../structunilink_1_1config_1_1ConfigItem.html',1,'unilink::config']]],
  ['configmanager_94',['ConfigManager',['../classunilink_1_1config_1_1ConfigManager.html',1,'unilink::config']]],
  ['configmanagerinterface_95',['ConfigManagerInterface',['../classunilink_1_1config_1_1ConfigManagerInterface.html',1,'unilink::config']]],
  ['configpresets_96',['ConfigPresets',['../classunilink_1_1config_1_1ConfigPresets.html',1,'unilink::config']]],
  ['configuration_97',['configuration',['../contrib_arch_runtime.html#autotoc_md212',1,'Backpressure Configuration'],['../contrib_arch.html#autotoc_md147',1,'Compile-Time Configuration'],['../contrib_testing.html#autotoc_md465',1,'CTest Configuration'],['../contrib_arch_runtime.html#autotoc_md196',1,'Retry Interval Configuration'],['../contrib_arch.html#autotoc_md148',1,'Runtime Configuration'],['../contrib_testing.html#autotoc_md464',1,'Test Configuration']]],
  ['configuration_20example_98',['Configuration Example',['../contrib_arch_runtime.html#autotoc_md192',1,'']]],
  ['configuration_20file_20format_99',['Configuration File Format',['../user_api_guide.html#autotoc_md575',1,'']]],
  ['configuration_20from_20file_100',['Load Configuration from File',['../user_api_guide.html#autotoc_md574',1,'']]],
  ['configuration_20management_101',['Configuration Management',['../user_api_guide.html#autotoc_md573',1,'']]],
  ['configuration_20management_20api_102',['configuration management api',['../contrib_build.html#autotoc_md269',1,'Full Build (includes Configuration Management API)'],['../contrib_build.html#autotoc_md267',1,'Minimal Build (without Configuration Management API)']]],
  ['configuration_20system_103',['Configuration System',['../contrib_arch.html#autotoc_md146',1,'']]],
  ['configurationexception_104',['ConfigurationException',['../classunilink_1_1diagnostics_1_1ConfigurationException.html',1,'unilink::diagnostics']]],
  ['configurations_105',['Build Configurations',['../contrib_build.html#autotoc_md266',1,'']]],
  ['configure_20and_20build_106',['Configure And Build',['../contrib_orin_nano_validation.html#autotoc_md375',1,'']]],
  ['conflicts_107',['Port Conflicts',['../contrib_testing.html#autotoc_md472',1,'']]],
  ['connect_20to_20server_108',['Can&apos;t connect to server?',['../user_quickstart.html#autotoc_md680',1,'']]],
  ['connection_109',['2. Server Closing Connection',['../user_troubleshooting.html#autotoc_md747',1,'']]],
  ['connection_20drops_20randomly_110',['Problem: Connection Drops Randomly',['../user_troubleshooting.html#autotoc_md745',1,'']]],
  ['connection_20issues_111',['Connection Issues',['../user_troubleshooting.html#autotoc_md735',1,'']]],
  ['connection_20limits_112',['Connection Limits',['../user_api_guide.html#autotoc_md603',1,'']]],
  ['connection_20limits_20optional_113',['Pattern 3: Connection Limits (optional)',['../user_quickstart.html#autotoc_md675',1,'']]],
  ['connection_20refused_114',['Problem: Connection Refused',['../user_troubleshooting.html#autotoc_md736',1,'']]],
  ['connection_20reuse_115',['2. Connection Reuse',['../user_performance.html#autotoc_md657',1,'']]],
  ['connection_20states_116',['Connection States',['../contrib_arch_runtime.html#autotoc_md190',1,'']]],
  ['connection_20timeout_117',['Problem: Connection Timeout',['../user_troubleshooting.html#autotoc_md741',1,'']]],
  ['connectioncontext_118',['ConnectionContext',['../classunilink_1_1wrapper_1_1ConnectionContext.html',1,'unilink::wrapper']]],
  ['connectionexception_119',['ConnectionException',['../classunilink_1_1diagnostics_1_1ConnectionException.html',1,'unilink::diagnostics']]],
  ['considerations_120',['considerations',['../contrib_arch_runtime.html#autotoc_md238',1,'Performance Considerations'],['../contrib_arch.html#autotoc_md150',1,'Performance Considerations']]],
  ['consistency_121',['5. Error Handling Consistency',['../contrib_arch_channel.html#autotoc_md7',1,'']]],
  ['construction_20validation_122',['1. Construction Validation',['../contrib_arch_memory.html#autotoc_md21',1,'']]],
  ['constructor_123',['constructor',['../user_api_guide.html#autotoc_md507',1,'Constructor'],['../user_api_guide.html#autotoc_md528',1,'Constructor'],['../user_api_guide.html#autotoc_md517',1,'Constructor']]],
  ['constructors_124',['constructors',['../user_api_guide.html#autotoc_md554',1,'Constructors'],['../user_api_guide.html#autotoc_md541',1,'Constructors']]],
  ['contents_125',['contents',['../user_performance.html#autotoc_md644',1,'Table of Contents'],['../user_api_guide.html#autotoc_md490',1,'Table of Contents'],['../user_troubleshooting.html#autotoc_md733',1,'Table of Contents'],['../contrib_testing.html#autotoc_md410',1,'Table of Contents'],['../contrib_arch_memory.html#autotoc_md10',1,'Table of Contents'],['../contrib_arch_runtime.html#autotoc_md171',1,'Table of Contents'],['../contrib_arch.html#autotoc_md98',1,'Table of Contents'],['../contrib_build.html#autotoc_md259',1,'Table of Contents']]],
  ['context_126',['context',['../contrib_arch_runtime.html#autotoc_md179',1,'✅ Callback Execution Context'],['../user_performance.html#autotoc_md647',1,'1. Threading Model &amp; IO Context'],['../contrib_arch.html#autotoc_md132',1,'Independent Context']]],
  ['context_20default_127',['Shared Context (Default)',['../contrib_arch.html#autotoc_md131',1,'']]],
  ['context_20for_20testing_20only_128',['1. Use Independent Context for Testing Only',['../user_api_guide.html#autotoc_md585',1,'']]],
  ['context_20management_129',['IO Context Management',['../contrib_arch.html#autotoc_md130',1,'']]],
  ['context_20ownership_20advanced_130',['IO Context Ownership (advanced)',['../user_api_guide.html#autotoc_md500',1,'']]],
  ['contexts_131',['2. Independent Contexts',['../contrib_arch.html#autotoc_md165',1,'']]],
  ['contexts_20have_20different_20ownership_20rules_132',['5. Managed and unmanaged external contexts have different ownership rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'']]],
  ['continuous_20integration_133',['continuous integration',['../contrib_arch_memory.html#autotoc_md94',1,'Continuous Integration'],['../contrib_testing.html#autotoc_md448',1,'Continuous Integration']]],
  ['contract_134',['contract',['../contrib_arch_wrapper.html#autotoc_md248',1,'3. &lt;tt&gt;auto_start(true)&lt;/tt&gt; follows the same startup contract'],['../contrib_arch_wrapper.html#autotoc_md252',1,'Callback Contract'],['../contrib_arch_wrapper.html#autotoc_md249',1,'External &lt;tt&gt;io_context&lt;/tt&gt; Contract'],['../contrib_arch_channel.html',1,'Transport Channel Contract'],['../contrib_arch_wrapper.html',1,'Wrapper Contract']]],
  ['contributor_20guide_135',['Contributor Guide',['../contrib_index.html',1,'']]],
  ['contributors_136',['🔧 For Contributors',['../index.html#autotoc_md486',1,'']]],
  ['control_137',['control',['../user_api_guide.html#autotoc_md579',1,'2. Use Explicit Lifecycle Control'],['../contrib_arch_runtime.html#autotoc_md200',1,'Manual Control']]],
  ['controls_138',['Build-Time Controls',['../contrib_test_structure.html#autotoc_md401',1,'']]],
  ['conversions_139',['conversions',['../contrib_arch_memory.html#autotoc_md23',1,'2. Safe Type Conversions'],['../contrib_arch_memory.html#autotoc_md68',1,'2. Type Conversions']]],
  ['copies_140',['1. Avoid Data Copies',['../user_performance.html#autotoc_md652',1,'']]],
  ['copy_20operations_141',['2. Zero-Copy Operations',['../contrib_arch.html#autotoc_md152',1,'']]],
  ['core_20components_142',['Core Components',['../contrib_arch.html#autotoc_md110',1,'']]],
  ['core_20concept_143',['Core Concept',['../user_api_guide.html#autotoc_md493',1,'']]],
  ['core_20dumps_144',['1. Enable Core Dumps',['../user_troubleshooting.html#autotoc_md773',1,'']]],
  ['core_20library_20dependencies_145',['Core Library Dependencies',['../user_requirements.html#autotoc_md691',1,'']]],
  ['core_20options_146',['Core Options',['../contrib_build.html#autotoc_md272',1,'']]],
  ['core_20principles_147',['2. Core Principles',['../contrib_arch_channel.html#autotoc_md4',1,'']]],
  ['core_20rules_148',['Core Rules',['../contrib_arch_wrapper.html#autotoc_md245',1,'']]],
  ['core_20tests_149',['Core Tests',['../contrib_testing.html#autotoc_md428',1,'']]],
  ['corruption_150',['Problem: Race Condition / Data Corruption',['../user_troubleshooting.html#autotoc_md802',1,'']]],
  ['coverage_151',['coverage',['../contrib_orin_nano_validation.html#autotoc_md380',1,'Automated Integration Coverage'],['../contrib_testing.html#autotoc_md478',1,'Code Coverage']]],
  ['coverage_20report_152',['coverage report',['../contrib_testing.html#autotoc_md479',1,'Generate Coverage Report'],['../contrib_testing.html#autotoc_md480',1,'View HTML Coverage Report']]],
  ['covers_153',['What Each Area Covers',['../contrib_test_structure.html#autotoc_md400',1,'']]],
  ['cpu_20usage_154',['Problem: High CPU Usage',['../user_troubleshooting.html#autotoc_md784',1,'']]],
  ['create_155',['create',['../classunilink_1_1config_1_1ConfigFactory.html#a69ad725f19260549b3d7282d84594fe5',1,'unilink::config::ConfigFactory']]],
  ['create_20a_20minimal_20serial_20terminal_156',['Step 2: Create A Minimal Serial Terminal',['../tutorial_04.html#autotoc_md861',1,'']]],
  ['create_20a_20receiver_157',['Step 1: Create A Receiver',['../tutorial_05.html#autotoc_md876',1,'']]],
  ['create_20a_20sender_158',['Step 2: Create A Sender',['../tutorial_05.html#autotoc_md878',1,'']]],
  ['create_20a_20uds_20client_159',['Step 2: Create A UDS Client',['../tutorial_03.html#autotoc_md848',1,'']]],
  ['create_20a_20uds_20server_160',['Step 1: Create A UDS Server',['../tutorial_03.html#autotoc_md846',1,'']]],
  ['create_20the_20client_161',['Step 1: Create The Client',['../tutorial_01.html#autotoc_md816',1,'']]],
  ['create_20the_20server_162',['Step 1: Create The Server',['../tutorial_02.html#autotoc_md831',1,'']]],
  ['create_5ffrom_5ffile_163',['create_from_file',['../classunilink_1_1config_1_1ConfigFactory.html#a1349da1432ca59942141f42f10e1ddc6',1,'unilink::config::ConfigFactory']]],
  ['create_5fwith_5fdefaults_164',['create_with_defaults',['../classunilink_1_1config_1_1ConfigFactory.html#a4edec9716691c78976092f69d6810ae5',1,'unilink::config::ConfigFactory']]],
  ['criteria_165',['Pass Criteria',['../contrib_orin_nano_validation.html#autotoc_md384',1,'']]],
  ['critical_20reliable_20data_166',['3. Critical Reliable Data',['../user_performance.html#autotoc_md663',1,'']]],
  ['ctest_20configuration_167',['CTest Configuration',['../contrib_testing.html#autotoc_md465',1,'']]],
  ['current_20bool_20api_168',['Current bool API',['../contrib_design_send_result.html#autotoc_md337',1,'']]],
  ['current_20server_20api_169',['Step 3: Understand The Current Server API',['../tutorial_02.html#autotoc_md835',1,'']]],
  ['currently_20registered_170',['Inspect What Is Currently Registered',['../contrib_test_structure.html#autotoc_md406',1,'']]],
  ['custom_20boost_20location_171',['Example 4: Build with Custom Boost Location',['../contrib_build.html#autotoc_md290',1,'']]],
  ['custom_20builders_172',['2. Custom Builders',['../contrib_arch.html#autotoc_md157',1,'']]],
  ['custom_20error_20handlers_173',['3. Custom Error Handlers',['../contrib_arch.html#autotoc_md158',1,'']]],
  ['custom_20format_174',['Custom Format',['../user_api_guide.html#autotoc_md570',1,'']]],
  ['custom_20installation_20directory_175',['Custom Installation Directory',['../contrib_build.html#autotoc_md315',1,'']]],
  ['custom_20installation_20prefix_176',['Custom Installation Prefix',['../contrib_build.html#autotoc_md331',1,'']]],
  ['custom_20integration_20test_177',['Example: Custom Integration Test',['../contrib_testing.html#autotoc_md460',1,'']]],
  ['custom_20tests_178',['custom tests',['../contrib_testing.html#autotoc_md462',1,'Running Custom Tests'],['../contrib_testing.html#autotoc_md457',1,'Writing Custom Tests']]],
  ['custom_20transports_179',['1. Custom Transports',['../contrib_arch.html#autotoc_md156',1,'']]]
];
