var searchData=
[
  ['data_0',['data',['../user_performance.html#autotoc_md663',1,'3. Critical Reliable Data'],['../classunilink_1_1wrapper_1_1MessageContext.html#a49d3f7b0aeac37cb41885b5fc2fa6423',1,'unilink::wrapper::MessageContext::data()'],['../contrib_arch_runtime.html#autotoc_md219',1,'Strategy 3: Drop Data']]],
  ['data_20buffer_1',['4. Safe Data Buffer',['../contrib_arch.html#autotoc_md138',1,'']]],
  ['data_20copies_2',['1. Avoid Data Copies',['../user_performance.html#autotoc_md652',1,'']]],
  ['data_20corruption_3',['Problem: Race Condition / Data Corruption',['../user_troubleshooting.html#autotoc_md802',1,'']]],
  ['data_20handling_4',['Safe Data Handling',['../contrib_arch_memory.html#autotoc_md17',1,'']]],
  ['data_20ownership_5',['&lt;tt&gt;MessageContext&lt;/tt&gt; Data Ownership',['../user_api_guide.html#autotoc_md496',1,'']]],
  ['data_20transfer_6',['Problem: Slow Data Transfer',['../user_troubleshooting.html#autotoc_md793',1,'']]],
  ['data_5fas_5fstring_7',['data_as_string',['../classunilink_1_1wrapper_1_1MessageContext.html#a8b634569a2e3dba8e2ed8645f85cf4e2',1,'unilink::wrapper::MessageContext']]],
  ['data_5fas_5fvector_8',['data_as_vector',['../classunilink_1_1wrapper_1_1MessageContext.html#ae984f5dd0b6ab5b9cbe099a52cffb0d0',1,'unilink::wrapper::MessageContext']]],
  ['debian_2011_9',['Debian 11+',['../contrib_build.html#autotoc_md302',1,'']]],
  ['debug_20build_10',['Debug Build',['../contrib_build.html#autotoc_md279',1,'']]],
  ['debug_20logging_11',['Enable Debug Logging',['../user_troubleshooting.html#autotoc_md806',1,'']]],
  ['debug_20reports_12',['4. Debug Reports',['../contrib_arch_memory.html#autotoc_md50',1,'']]],
  ['debugging_13',['debugging',['../user_api_guide.html#autotoc_md581',1,'4. Enable Logging for Debugging'],['../user_troubleshooting.html#autotoc_md807',1,'Use GDB for Debugging']]],
  ['debugging_20tips_14',['Debugging Tips',['../user_troubleshooting.html#autotoc_md805',1,'']]],
  ['debugging_20with_20tcpdump_15',['Network Debugging with tcpdump',['../user_troubleshooting.html#autotoc_md808',1,'']]],
  ['default_16',['default',['../contrib_build.html#autotoc_md277',1,'Release Build (Default)'],['../contrib_arch.html#autotoc_md131',1,'Shared Context (Default)']]],
  ['default_20behavior_17',['Default Behavior',['../contrib_arch_runtime.html#autotoc_md195',1,'']]],
  ['definitions_18',['Type Definitions',['../contrib_design_send_result.html#autotoc_md341',1,'']]],
  ['denied_20during_20install_19',['Problem: Permission Denied During Install',['../contrib_build.html#autotoc_md327',1,'']]],
  ['dependencies_20',['dependencies',['../user_requirements.html#autotoc_md691',1,'Core Library Dependencies'],['../user_requirements.html#autotoc_md690',1,'Dependencies'],['../user_installation.html#autotoc_md630',1,'Option B: Plain CMake with existing dependencies']]],
  ['dependency_20details_21',['Dependency Details',['../user_requirements.html#autotoc_md692',1,'']]],
  ['dependency_20injection_22',['dependency injection',['../contrib_arch.html#autotoc_md164',1,'1. Dependency Injection'],['../contrib_arch.html#autotoc_md118',1,'2. Dependency Injection']]],
  ['deprecation_20policy_23',['Deprecation Policy',['../user_api_stability.html#autotoc_md610',1,'']]],
  ['design_24',['design',['../user_api_guide.html#autotoc_md582',1,'5. Use Member Functions for OOP Design'],['../contrib_design_send_result.html#autotoc_md350',1,'Phase 1: Design'],['../contrib_design_send_result.html',1,'SendResult API Design']]],
  ['design_20goals_25',['Design Goals',['../contrib_arch.html#autotoc_md101',1,'']]],
  ['design_20notes_26',['design notes',['../contrib_index.html#autotoc_md365',1,'Design Notes'],['../contrib_design.html',1,'Design Notes']]],
  ['design_20only_20apis_27',['design only apis',['../user_api_stability.html#autotoc_md609',1,'Design-Only APIs'],['../user_transport_matrix.html#autotoc_md731',1,'Planned / Design-Only APIs']]],
  ['design_20patterns_28',['Design Patterns',['../contrib_arch.html#autotoc_md116',1,'']]],
  ['details_29',['Dependency Details',['../user_requirements.html#autotoc_md692',1,'']]],
  ['detected_30',['Problem: Memory Leak Detected',['../user_troubleshooting.html#autotoc_md799',1,'']]],
  ['detection_31',['2. Leak Detection',['../contrib_arch_memory.html#autotoc_md46',1,'']]],
  ['detects_32',['What ASan Detects',['../contrib_arch_memory.html#autotoc_md57',1,'']]],
  ['development_20build_33',['Example 2: Development Build',['../contrib_build.html#autotoc_md286',1,'']]],
  ['development_20options_34',['Development Options',['../contrib_build.html#autotoc_md273',1,'']]],
  ['development_20tooling_35',['Development &amp; Tooling',['../contrib_arch.html#autotoc_md160',1,'']]],
  ['device_20path_36',['Step 1: Choose A Device Path',['../tutorial_04.html#autotoc_md859',1,'']]],
  ['device_20paths_37',['Device Paths',['../user_api_guide.html#autotoc_md531',1,'']]],
  ['diagram_38',['diagram',['../contrib_arch_runtime.html#autotoc_md174',1,'Architecture Diagram'],['../contrib_arch_runtime.html#autotoc_md188',1,'State Machine Diagram']]],
  ['different_20about_20udp_39',['What Is Different About UDP',['../tutorial_05.html#autotoc_md884',1,'']]],
  ['different_20ownership_20rules_40',['5. Managed and unmanaged external contexts have different ownership rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'']]],
  ['different_20port_41',['2. Use Different Port',['../user_troubleshooting.html#autotoc_md752',1,'']]],
  ['directory_42',['Custom Installation Directory',['../contrib_build.html#autotoc_md315',1,'']]],
  ['distributions_43',['Other Linux Distributions',['../user_requirements.html#autotoc_md706',1,'']]],
  ['do_44',['do',['../contrib_arch_memory.html#autotoc_md65',1,'✅ DO'],['../contrib_arch_memory.html#autotoc_md81',1,'✅ DO'],['../contrib_arch_memory.html#autotoc_md69',1,'✅ DO'],['../contrib_arch_memory.html#autotoc_md77',1,'✅ DO'],['../contrib_arch_runtime.html#autotoc_md227',1,'✅ DO'],['../contrib_arch_runtime.html#autotoc_md231',1,'✅ DO'],['../contrib_arch_runtime.html#autotoc_md235',1,'✅ DO'],['../contrib_arch_memory.html#autotoc_md73',1,'✅ DO']]],
  ['docs_45',['docs',['../contrib_index.html#autotoc_md367',1,'Quick Links (User Docs)'],['../contrib_orin_nano_validation.html#autotoc_md391',1,'Related Docs'],['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2README.html',1,'unilink-docs']]],
  ['documentation_46',['documentation',['../contrib_release_checklist.html#autotoc_md395',1,'4. Documentation'],['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2README.html#autotoc_md905',1,'Documentation'],['../index.html',1,'Unilink Documentation']]],
  ['documentation_20generation_47',['Documentation Generation',['../contrib_arch.html#autotoc_md161',1,'']]],
  ['don_20t_48',['don t',['../contrib_arch_memory.html#autotoc_md70',1,'❌ DON&apos;T'],['../contrib_arch_runtime.html#autotoc_md236',1,'❌ DON&apos;T'],['../contrib_arch_runtime.html#autotoc_md232',1,'❌ DON&apos;T'],['../contrib_arch_runtime.html#autotoc_md228',1,'❌ DON&apos;T'],['../contrib_arch_memory.html#autotoc_md78',1,'❌ DON&apos;T'],['../contrib_arch_memory.html#autotoc_md82',1,'❌ DON&apos;T'],['../contrib_arch_memory.html#autotoc_md74',1,'❌ DON&apos;T'],['../contrib_arch_memory.html#autotoc_md66',1,'❌ DON&apos;T']]],
  ['double_5ffree_49',['double_free',['../namespaceunilink_1_1memory_1_1memory__validator.html#a433dec67ba6ef6f8d78d1caee66f79c1',1,'unilink::memory::memory_validator']]],
  ['download_20and_20extract_50',['Step 1: Download and extract',['../user_installation.html#autotoc_md634',1,'']]],
  ['doxygen_20api_20reference_51',['Generated Doxygen API Reference',['../user_index.html#autotoc_md617',1,'']]],
  ['drop_20data_52',['Strategy 3: Drop Data',['../contrib_arch_runtime.html#autotoc_md219',1,'']]],
  ['dropaccounting_53',['DropAccounting',['../structunilink_1_1transport_1_1queue__util_1_1DropAccounting.html',1,'unilink::transport::queue_util']]],
  ['drops_20packets_54',['Problem: UDP with Reliable Strategy Still Drops Packets',['../user_troubleshooting.html#autotoc_md781',1,'']]],
  ['drops_20randomly_55',['Problem: Connection Drops Randomly',['../user_troubleshooting.html#autotoc_md745',1,'']]],
  ['dumps_56',['1. Enable Core Dumps',['../user_troubleshooting.html#autotoc_md773',1,'']]],
  ['during_20build_57',['Problem: Out of Memory During Build',['../contrib_build.html#autotoc_md326',1,'']]],
  ['during_20install_58',['Problem: Permission Denied During Install',['../contrib_build.html#autotoc_md327',1,'']]]
];
