var searchData=
[
  ['machine_0',['Reconnection Policy &amp; State Machine',['../contrib_arch_runtime.html#autotoc_md187',1,'']]],
  ['machine_20diagram_1',['State Machine Diagram',['../contrib_arch_runtime.html#autotoc_md188',1,'']]],
  ['make_2',['Ninja Build System (Faster than Make)',['../contrib_build.html#autotoc_md311',1,'']]],
  ['managed_20and_20unmanaged_20external_20contexts_20have_20different_20ownership_20rules_3',['5. Managed and unmanaged external contexts have different ownership rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'']]],
  ['managed_20vcpkg_20setup_4',['Option A: Repository-managed vcpkg setup',['../user_installation.html#autotoc_md629',1,'']]],
  ['management_5',['management',['../contrib_arch_memory.html#autotoc_md64',1,'1. Buffer Management'],['../user_performance.html#backpressure-management',1,'Backpressure Management'],['../user_api_guide.html#autotoc_md573',1,'Configuration Management'],['../contrib_arch.html#autotoc_md130',1,'IO Context Management'],['../contrib_arch.html#autotoc_md134',1,'Memory Management'],['../contrib_arch_memory.html#autotoc_md29',1,'Thread-Safe State Management']]],
  ['management_20api_6',['management api',['../contrib_build.html#autotoc_md269',1,'Full Build (includes Configuration Management API)'],['../contrib_build.html#autotoc_md267',1,'Minimal Build (without Configuration Management API)']]],
  ['manual_20boost_20path_7',['Manual Boost Path',['../user_troubleshooting.html#autotoc_md769',1,'']]],
  ['manual_20control_8',['Manual Control',['../contrib_arch_runtime.html#autotoc_md200',1,'']]],
  ['manual_20virtual_20serial_20pair_9',['Manual Virtual Serial Pair',['../contrib_orin_nano_validation.html#autotoc_md381',1,'']]],
  ['many_20retries_10',['2. Too Many Retries',['../user_troubleshooting.html#autotoc_md786',1,'']]],
  ['matrix_11',['matrix',['../contrib_testing.html#autotoc_md451',1,'CI/CD Build Matrix'],['../user_transport_matrix.html',1,'Transport Feature Matrix']]],
  ['meaning_12',['Transport Meaning',['../user_api_guide.html#autotoc_md598',1,'']]],
  ['member_20functions_13',['With Member Functions',['../user_api_guide.html#autotoc_md511',1,'']]],
  ['member_20functions_20for_20oop_20design_14',['5. Use Member Functions for OOP Design',['../user_api_guide.html#autotoc_md582',1,'']]],
  ['memory_20during_20build_15',['Problem: Out of Memory During Build',['../contrib_build.html#autotoc_md326',1,'']]],
  ['memory_20issues_16',['memory issues',['../user_troubleshooting.html#autotoc_md798',1,'Memory Issues'],['../contrib_testing.html#autotoc_md474',1,'Memory Issues']]],
  ['memory_20leak_20detected_17',['Problem: Memory Leak Detected',['../user_troubleshooting.html#autotoc_md799',1,'']]],
  ['memory_20leaks_18',['1. Fix Memory Leaks',['../user_troubleshooting.html#autotoc_md790',1,'']]],
  ['memory_20management_19',['Memory Management',['../contrib_arch.html#autotoc_md134',1,'']]],
  ['memory_20optimization_20',['Memory Optimization',['../user_performance.html#autotoc_md651',1,'']]],
  ['memory_20pool_21',['2. Memory Pool',['../contrib_arch.html#autotoc_md136',1,'']]],
  ['memory_20pooling_22',['3. Memory Pooling',['../contrib_arch.html#autotoc_md153',1,'']]],
  ['memory_20safety_23',['memory safety',['../contrib_arch_runtime.html#autotoc_md223',1,'Memory Safety'],['../contrib_arch_memory.html#autotoc_md89',1,'Testing Memory Safety']]],
  ['memory_20safety_20architecture_24',['Memory Safety Architecture',['../contrib_arch_memory.html',1,'contrib_arch']]],
  ['memory_20safety_20benefits_25',['Memory Safety Benefits',['../contrib_arch_memory.html#autotoc_md84',1,'']]],
  ['memory_20safety_20model_26',['Memory Safety Model',['../contrib_arch_memory.html#autotoc_md13',1,'']]],
  ['memory_20safety_20tests_27',['Memory Safety Tests',['../contrib_testing.html#autotoc_md430',1,'']]],
  ['memory_20safety_20validation_28',['Memory Safety Validation',['../contrib_testing.html#autotoc_md439',1,'']]],
  ['memory_20tracking_29',['memory tracking',['../contrib_arch.html#autotoc_md137',1,'3. Memory Tracking'],['../contrib_arch_memory.html#autotoc_md76',1,'4. Memory Tracking'],['../contrib_testing.html#autotoc_md440',1,'Built-in Memory Tracking'],['../contrib_arch_memory.html#autotoc_md41',1,'Built-in Memory Tracking'],['../contrib_arch_memory.html#autotoc_md40',1,'Memory Tracking']]],
  ['memory_20usage_30',['Problem: High Memory Usage',['../user_troubleshooting.html#autotoc_md789',1,'']]],
  ['memory_20validation_31',['3. Memory Validation',['../contrib_arch_memory.html#autotoc_md25',1,'']]],
  ['memory_5faccessible_32',['memory_accessible',['../namespaceunilink_1_1memory_1_1memory__validator.html#a3a349f1dda39edf3f624186afc02aceb',1,'unilink::memory::memory_validator']]],
  ['memory_5faligned_33',['memory_aligned',['../namespaceunilink_1_1memory_1_1memory__validator.html#a6c80480ebe24b4445b0fe679e6add166',1,'unilink::memory::memory_validator']]],
  ['memoryexception_34',['MemoryException',['../classunilink_1_1diagnostics_1_1MemoryException.html',1,'unilink::diagnostics']]],
  ['memorypatterngenerator_35',['MemoryPatternGenerator',['../classunilink_1_1memory_1_1MemoryPatternGenerator.html',1,'unilink::memory']]],
  ['memorypool_36',['MemoryPool',['../classunilink_1_1memory_1_1MemoryPool.html',1,'unilink::memory']]],
  ['memorystats_37',['MemoryStats',['../structunilink_1_1memory_1_1MemoryTracker_1_1MemoryStats.html',1,'unilink::memory::MemoryTracker']]],
  ['memorytracker_38',['MemoryTracker',['../classunilink_1_1memory_1_1MemoryTracker.html',1,'unilink::memory']]],
  ['memoryvalidator_39',['MemoryValidator',['../classunilink_1_1memory_1_1MemoryValidator.html',1,'unilink::memory']]],
  ['message_40',['message',['../classunilink_1_1wrapper_1_1ErrorContext.html#a9f7fc6c812b11ff1d77aa71233a3221c',1,'unilink::wrapper::ErrorContext']]],
  ['message_20handling_41',['Framed Message Handling',['../user_api_guide.html#autotoc_md497',1,'']]],
  ['messagecallback_42',['MessageCallback',['../classunilink_1_1framer_1_1IFramer.html#ae5ee86cbd7ded1a4f845f3889b4189ad',1,'unilink::framer::IFramer']]],
  ['messagecontext_43',['MessageContext',['../classunilink_1_1wrapper_1_1MessageContext.html',1,'unilink::wrapper']]],
  ['messagecontext_20tt_20data_20ownership_44',['&lt;tt&gt;MessageContext&lt;/tt&gt; Data Ownership',['../user_api_guide.html#autotoc_md496',1,'']]],
  ['messages_45',['messages',['../user_performance.html#autotoc_md656',1,'1. Batch Small Messages'],['../user_troubleshooting.html#autotoc_md794',1,'1. Batch Small Messages']]],
  ['method_201_3a_20vcpkg_20recommended_46',['Method 1: vcpkg (Recommended)',['../user_installation.html#autotoc_md625',1,'']]],
  ['method_202_3a_20install_20from_20source_47',['Method 2: Install from Source',['../user_installation.html#autotoc_md628',1,'']]],
  ['method_203_3a_20release_20packages_48',['Method 3: Release Packages',['../user_installation.html#autotoc_md633',1,'']]],
  ['method_204_3a_20git_20submodule_20integration_49',['Method 4: Git Submodule Integration',['../user_installation.html#autotoc_md637',1,'']]],
  ['method_20pattern_50',['6. Template Method Pattern',['../contrib_arch.html#autotoc_md122',1,'']]],
  ['methods_51',['methods',['../contrib_arch.html#autotoc_md127',1,'1. Runtime Methods'],['../user_api_guide.html#autotoc_md508',1,'Builder Methods'],['../user_api_guide.html#autotoc_md529',1,'Builder Methods'],['../user_api_guide.html#autotoc_md518',1,'Builder Methods'],['../contrib_arch_runtime.html#autotoc_md177',1,'Concurrent Runtime Methods'],['../user_installation.html#autotoc_md624',1,'Installation Methods'],['../user_api_guide.html#autotoc_md519',1,'Instance Methods'],['../user_api_guide.html#autotoc_md530',1,'Instance Methods'],['../user_api_guide.html#autotoc_md509',1,'Instance Methods']]],
  ['methods_20all_20builders_52',['Common Methods (All Builders)',['../user_api_guide.html#autotoc_md494',1,'']]],
  ['methods_20udpclient_53',['methods udpclient',['../user_api_guide.html#autotoc_md542',1,'Builder Methods (UdpClient)'],['../user_api_guide.html#autotoc_md544',1,'Instance Methods (UdpClient)']]],
  ['methods_20udpserver_54',['Builder Methods (UdpServer)',['../user_api_guide.html#autotoc_md543',1,'']]],
  ['methods_20uds_20client_55',['methods uds client',['../user_api_guide.html#autotoc_md556',1,'Builder Methods (UDS Client)'],['../user_api_guide.html#autotoc_md557',1,'Instance Methods (UDS Client)']]],
  ['methods_20uds_20server_56',['methods uds server',['../user_api_guide.html#autotoc_md555',1,'Builder Methods (UDS Server)'],['../user_api_guide.html#autotoc_md558',1,'Instance Methods (UDS Server)']]],
  ['migration_20plan_57',['Migration Plan',['../contrib_design_send_result.html#autotoc_md349',1,'']]],
  ['min_5ferror_5flevel_58',['min_error_level',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#af64cce19161c0671d60bc079ece9e4e2',1,'unilink::diagnostics::ErrorHandler']]],
  ['minimal_20build_20without_20configuration_20management_20api_59',['Minimal Build (without Configuration Management API)',['../contrib_build.html#autotoc_md267',1,'']]],
  ['minimal_20production_20build_60',['Example 1: Minimal Production Build',['../contrib_build.html#autotoc_md284',1,'']]],
  ['minimal_20serial_20terminal_61',['Step 2: Create A Minimal Serial Terminal',['../tutorial_04.html#autotoc_md861',1,'']]],
  ['minimum_20compiler_20versions_62',['Minimum Compiler Versions',['../user_requirements.html#autotoc_md695',1,'']]],
  ['mode_63',['Single Client Mode',['../user_api_guide.html#autotoc_md521',1,'']]],
  ['model_64',['model',['../contrib_arch_memory.html#autotoc_md13',1,'Memory Safety Model'],['../contrib_arch_runtime.html',1,'Runtime Behavior Model'],['../contrib_arch.html#autotoc_md126',1,'Thread Safety Model'],['../contrib_arch.html#autotoc_md124',1,'Threading Model']]],
  ['model_20callback_20execution_65',['Threading Model &amp; Callback Execution',['../contrib_arch_runtime.html#autotoc_md173',1,'']]],
  ['model_20io_20context_66',['1. Threading Model &amp; IO Context',['../user_performance.html#autotoc_md647',1,'']]],
  ['model_20summary_67',['Threading Model Summary',['../contrib_arch_runtime.html#autotoc_md185',1,'']]],
  ['module_68',['GPS Module',['../user_api_guide.html#autotoc_md534',1,'']]],
  ['monitoring_69',['monitoring',['../contrib_arch_memory.html#autotoc_md48',1,'3. Performance Monitoring'],['../contrib_arch_runtime.html#autotoc_md221',1,'Backpressure Monitoring']]],
  ['more_70',['more',['../tutorial_01.html#autotoc_md824',1,'Use The Full Example If You Want More'],['../tutorial_02.html#autotoc_md839',1,'Use The Full Example Programs For More']]],
  ['move_20and_20shared_20buffer_20sends_71',['Move And Shared Buffer Sends',['../user_api_guide.html#autotoc_md498',1,'']]]
];
