var searchData=
[
  ['a_20device_20path_0',['Step 1: Choose A Device Path',['../tutorial_04.html#autotoc_md859',1,'']]],
  ['a_20minimal_20serial_20terminal_1',['Step 2: Create A Minimal Serial Terminal',['../tutorial_04.html#autotoc_md861',1,'']]],
  ['a_20receiver_2',['Step 1: Create A Receiver',['../tutorial_05.html#autotoc_md876',1,'']]],
  ['a_20second_20terminal_3',['Step 4: Test With A Second Terminal',['../tutorial_04.html#autotoc_md865',1,'']]],
  ['a_20sender_4',['Step 2: Create A Sender',['../tutorial_05.html#autotoc_md878',1,'']]],
  ['a_20strategy_5',['1. Choosing a Strategy',['../user_performance.html#autotoc_md660',1,'']]],
  ['a_20tcp_20server_6',['Building a TCP Server',['../tutorial_02.html',1,'user_tutorials']]],
  ['a_20test_20server_7',['Step 3: Run Against A Test Server',['../tutorial_01.html#autotoc_md820',1,'']]],
  ['a_20uds_20client_8',['Step 2: Create A UDS Client',['../tutorial_03.html#autotoc_md848',1,'']]],
  ['a_20uds_20server_9',['Step 1: Create A UDS Server',['../tutorial_03.html#autotoc_md846',1,'']]],
  ['a_3a_20repository_20managed_20vcpkg_20setup_10',['Option A: Repository-managed vcpkg setup',['../user_installation.html#autotoc_md629',1,'']]],
  ['abi_20compatibility_11',['ABI Compatibility',['../user_api_stability.html#autotoc_md608',1,'']]],
  ['about_20udp_12',['What Is Different About UDP',['../tutorial_05.html#autotoc_md884',1,'']]],
  ['access_13',['✅ Thread-Safe State Access',['../contrib_arch_runtime.html#autotoc_md183',1,'']]],
  ['acquisition_20is_20initialization_14',['5. RAII (Resource Acquisition Is Initialization)',['../contrib_arch.html#autotoc_md121',1,'']]],
  ['actions_20integration_15',['GitHub Actions Integration',['../contrib_testing.html#autotoc_md449',1,'']]],
  ['add_20include_20path_16',['2. Add Include Path',['../user_troubleshooting.html#autotoc_md758',1,'']]],
  ['add_20submodule_17',['Step 1: Add submodule',['../user_installation.html#autotoc_md638',1,'']]],
  ['addresssanitizer_18',['Enable AddressSanitizer',['../contrib_arch_memory.html#autotoc_md55',1,'']]],
  ['addresssanitizer_20asan_19',['AddressSanitizer (ASan)',['../contrib_testing.html#autotoc_md442',1,'']]],
  ['addresssanitizer_20support_20',['AddressSanitizer Support',['../contrib_arch_memory.html#autotoc_md54',1,'']]],
  ['adjustments_21',['Common Adjustments',['../tutorial_04.html#autotoc_md867',1,'']]],
  ['advanced_22',['IO Context Ownership (advanced)',['../user_api_guide.html#autotoc_md500',1,'']]],
  ['advanced_20build_20examples_23',['Advanced Build Examples',['../contrib_build.html#autotoc_md283',1,'']]],
  ['advanced_20examples_24',['advanced examples',['../user_api_guide.html#autotoc_md510',1,'Advanced Examples'],['../user_api_guide.html#autotoc_md520',1,'Advanced Examples'],['../user_api_guide.html#autotoc_md545',1,'Advanced Examples'],['../user_api_guide.html#autotoc_md532',1,'Advanced Examples']]],
  ['advanced_20headers_25',['Supported But Advanced Headers',['../user_api_stability.html#autotoc_md605',1,'']]],
  ['after_20stop_26',['3. Stop Semantics: No Callbacks After Stop()',['../contrib_arch_channel.html#autotoc_md5',1,'']]],
  ['after_20tt_20stop_20tt_20returns_27',['7. No wrapper callbacks after &lt;tt&gt;stop()&lt;/tt&gt; returns',['../contrib_arch_wrapper.html#autotoc_md254',1,'']]],
  ['against_20a_20test_20server_28',['Step 3: Run Against A Test Server',['../tutorial_01.html#autotoc_md820',1,'']]],
  ['agnostic_20expectations_29',['Transport-Agnostic Expectations',['../contrib_arch_wrapper.html#autotoc_md256',1,'']]],
  ['alive_20not_20set_30',['3. Keep-Alive Not Set',['../user_troubleshooting.html#autotoc_md748',1,'']]],
  ['all_20builders_31',['Common Methods (All Builders)',['../user_api_guide.html#autotoc_md494',1,'']]],
  ['all_20input_32',['Validate All Input',['../user_api_guide.html#autotoc_md601',1,'']]],
  ['all_20registered_20tests_33',['Run All Registered Tests',['../contrib_test_structure.html#autotoc_md403',1,'']]],
  ['all_20tests_34',['all tests',['../contrib_testing.html#autotoc_md413',1,'Build and Run All Tests'],['../contrib_testing.html#autotoc_md418',1,'Run All Tests']]],
  ['allocation_20tracking_35',['1. Allocation Tracking',['../contrib_arch_memory.html#autotoc_md44',1,'']]],
  ['allocationinfo_36',['AllocationInfo',['../structunilink_1_1memory_1_1MemoryTracker_1_1AllocationInfo.html',1,'unilink::memory::MemoryTracker']]],
  ['already_20in_20use_37',['already in use',['../user_quickstart.html#autotoc_md681',1,'Port already in use?'],['../user_troubleshooting.html#autotoc_md750',1,'Problem: Port Already in Use']]],
  ['always_20handle_20errors_38',['1. Always Handle Errors',['../user_api_guide.html#autotoc_md578',1,'']]],
  ['an_20install_20prefix_39',['Step 2: Choose an install prefix',['../user_installation.html#autotoc_md635',1,'']]],
  ['and_20backpressure_20semantics_40',['Send And Backpressure Semantics',['../user_api_guide.html#autotoc_md590',1,'']]],
  ['and_20build_41',['Configure And Build',['../contrib_orin_nano_validation.html#autotoc_md375',1,'']]],
  ['and_20extract_42',['Step 1: Download and extract',['../user_installation.html#autotoc_md634',1,'']]],
  ['and_20run_43',['Step 3: Build And Run',['../tutorial_04.html#autotoc_md863',1,'']]],
  ['and_20run_20all_20tests_44',['Build and Run All Tests',['../contrib_testing.html#autotoc_md413',1,'']]],
  ['and_20shared_20buffer_20sends_45',['Move And Shared Buffer Sends',['../user_api_guide.html#autotoc_md498',1,'']]],
  ['and_20test_46',['2. Build And Test',['../contrib_release_checklist.html#autotoc_md393',1,'']]],
  ['and_20test_20status_47',['Build And Test Status',['../contrib_impl_status.html#autotoc_md358',1,'']]],
  ['and_20tests_48',['Examples and Tests',['../index.html#autotoc_md488',1,'']]],
  ['and_20tt_20stop_20tt_20are_20safe_49',['2. Repeated &lt;tt&gt;start()&lt;/tt&gt; and &lt;tt&gt;stop()&lt;/tt&gt; are safe',['../contrib_arch_wrapper.html#autotoc_md247',1,'']]],
  ['and_20unmanaged_20external_20contexts_20have_20different_20ownership_20rules_50',['5. Managed and unmanaged external contexts have different ownership rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'']]],
  ['api_51',['api',['../user_api_guide.html#autotoc_md492',1,'Builder API'],['../contrib_design_send_result.html#autotoc_md337',1,'Current bool API'],['../contrib_build.html#autotoc_md269',1,'Full Build (includes Configuration Management API)'],['../contrib_build.html#autotoc_md267',1,'Minimal Build (without Configuration Management API)'],['../contrib_design_send_result.html#autotoc_md351',1,'Phase 2: Experimental API'],['../contrib_design_send_result.html#autotoc_md352',1,'Phase 3: Official 0.8 API'],['../contrib_design_send_result.html#autotoc_md340',1,'Proposed API'],['../tutorial_02.html#autotoc_md835',1,'Step 3: Understand The Current Server API']]],
  ['api_20compatibility_52',['API Compatibility',['../contrib_design_send_result.html#autotoc_md347',1,'']]],
  ['api_20design_53',['SendResult API Design',['../contrib_design_send_result.html',1,'']]],
  ['api_20guide_54',['Unilink API Guide',['../user_api_guide.html',1,'user_index']]],
  ['api_20layer_55',['api layer',['../contrib_arch.html#autotoc_md105',1,'1. Builder API Layer'],['../contrib_arch.html#autotoc_md106',1,'2. Wrapper API Layer']]],
  ['api_20names_56',['API Names',['../contrib_design_send_result.html#autotoc_md342',1,'']]],
  ['api_20patterns_20used_20in_20this_20tutorial_57',['API Patterns Used In This Tutorial',['../tutorial_01.html#autotoc_md822',1,'']]],
  ['api_20reference_58',['api reference',['../user_api_guide.html#autotoc_md540',1,'API Reference'],['../user_api_guide.html#autotoc_md527',1,'API Reference'],['../user_index.html#autotoc_md616',1,'API Reference'],['../user_api_guide.html#autotoc_md553',1,'API Reference'],['../user_api_guide.html#autotoc_md516',1,'API Reference'],['../user_api_guide.html#autotoc_md506',1,'API Reference'],['../user_index.html#autotoc_md617',1,'Generated Doxygen API Reference']]],
  ['api_20stability_20policy_59',['API Stability Policy',['../user_api_stability.html',1,'']]],
  ['api_20support_60',['api support',['../user_transport_matrix.html#autotoc_md723',1,'Send API Support'],['../user_transport_matrix.html#autotoc_md724',1,'Server API Support']]],
  ['api_20surface_61',['C++ API Surface',['../contrib_impl_status.html#autotoc_md356',1,'']]],
  ['apis_62',['apis',['../user_api_stability.html#autotoc_md609',1,'Design-Only APIs'],['../user_transport_matrix.html#autotoc_md731',1,'Planned / Design-Only APIs']]],
  ['application_20exits_20too_20quickly_63',['3. Application Exits Too Quickly',['../user_troubleshooting.html#autotoc_md779',1,'']]],
  ['applications_20using_20unilink_64',['For Applications Using unilink',['../user_requirements.html#autotoc_md699',1,'']]],
  ['appropriate_20retry_20interval_65',['1. Choose Appropriate Retry Interval',['../contrib_arch_runtime.html#autotoc_md203',1,'']]],
  ['appropriate_20retry_20intervals_66',['3. Set Appropriate Retry Intervals',['../user_api_guide.html#autotoc_md580',1,'']]],
  ['arch_20linux_67',['Arch Linux',['../contrib_build.html#autotoc_md306',1,'']]],
  ['architecture_68',['architecture',['../contrib_index.html#autotoc_md363',1,'Architecture'],['../contrib_arch.html#autotoc_md103',1,'Layered Architecture'],['../contrib_arch_memory.html',1,'Memory Safety Architecture'],['../contrib_arch.html#autotoc_md163',1,'Testing Architecture'],['../contrib_arch.html',1,'Unilink System Architecture']]],
  ['architecture_20diagram_69',['Architecture Diagram',['../contrib_arch_runtime.html#autotoc_md174',1,'']]],
  ['arduino_20communication_70',['Arduino Communication',['../user_api_guide.html#autotoc_md533',1,'']]],
  ['are_20normalized_71',['8. Generic fallback errors are normalized',['../contrib_arch_wrapper.html#autotoc_md255',1,'']]],
  ['are_20safe_72',['2. Repeated &lt;tt&gt;start()&lt;/tt&gt; and &lt;tt&gt;stop()&lt;/tt&gt; are safe',['../contrib_arch_wrapper.html#autotoc_md247',1,'']]],
  ['area_20covers_73',['What Each Area Covers',['../contrib_test_structure.html#autotoc_md400',1,'']]],
  ['arm64_20jetson_20orin_20nano_74',['Ubuntu ARM64 / Jetson Orin Nano',['../user_requirements.html#autotoc_md704',1,'']]],
  ['as_20subdirectory_75',['3. Use as Subdirectory',['../user_troubleshooting.html#autotoc_md759',1,'']]],
  ['asan_76',['asan',['../contrib_testing.html#autotoc_md442',1,'AddressSanitizer (ASan)'],['../contrib_arch_memory.html#autotoc_md59',1,'Running with ASan']]],
  ['asan_20detects_77',['What ASan Detects',['../contrib_arch_memory.html#autotoc_md57',1,'']]],
  ['assets_78',['assets',['../contrib_release_checklist.html#autotoc_md396',1,'5. Release Assets'],['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2docs_2assets_2logo_2README.html',1,'unilink Logo Assets']]],
  ['async_20logging_79',['async logging',['../user_performance.html#autotoc_md648',1,'2. Async Logging'],['../user_api_guide.html#autotoc_md586',1,'2. Enable Async Logging'],['../user_troubleshooting.html#autotoc_md796',1,'3. Enable Async Logging'],['../user_api_guide.html#autotoc_md569',1,'Async Logging']]],
  ['async_20pattern_80',['The Async Pattern',['../user_tutorial_async.html#autotoc_md894',1,'']]],
  ['async_20vs_20sync_81',['4. When to Use Async vs Sync',['../user_tutorial_async.html#autotoc_md901',1,'']]],
  ['async_5flogging_5fenabled_82',['async_logging_enabled',['../classunilink_1_1diagnostics_1_1Logger.html#a3dfe3e110e30c23ec9800a4ef18c0f51',1,'unilink::diagnostics::Logger']]],
  ['asynchronous_20example_83',['Asynchronous Example',['../user_api_guide.html#autotoc_md502',1,'']]],
  ['asynchronous_20i_20o_84',['1. Asynchronous I/O',['../contrib_arch.html#autotoc_md151',1,'']]],
  ['asynchronous_20programming_20patterns_85',['Asynchronous Programming Patterns',['../user_tutorial_async.html',1,'']]],
  ['asynchronously_86',['Starting Synchronously vs. Asynchronously',['../user_api_guide.html#autotoc_md501',1,'']]],
  ['asynclogconfig_87',['AsyncLogConfig',['../structunilink_1_1diagnostics_1_1AsyncLogConfig.html',1,'unilink::diagnostics']]],
  ['atomicstate_88',['atomicstate',['../classunilink_1_1concurrency_1_1AtomicState.html',1,'unilink::concurrency::AtomicState&lt; StateType &gt;'],['../contrib_arch_memory.html#autotoc_md32',1,'AtomicState']]],
  ['auto_20reconnection_89',['Pattern 1: Auto-Reconnection',['../user_quickstart.html#autotoc_md673',1,'']]],
  ['auto_5fstart_90',['auto_start',['../classunilink_1_1builder_1_1UdsClientBuilder.html#a39a1256e8ac5ccf3f051491631b5ad9f',1,'unilink::builder::UdsClientBuilder::auto_start()'],['../classunilink_1_1builder_1_1BuilderInterface.html#a7436fef714fa8126bb29e55d13f0e849',1,'unilink::builder::BuilderInterface::auto_start()'],['../classunilink_1_1builder_1_1SerialBuilder.html#a5446387d77dd3a743393645cd565b7ce',1,'unilink::builder::SerialBuilder::auto_start()'],['../classunilink_1_1builder_1_1TcpClientBuilder.html#ac82e8d1573a814f8566f1c1514ae84a0',1,'unilink::builder::TcpClientBuilder::auto_start()'],['../classunilink_1_1builder_1_1TcpServerBuilder.html#aa729248f31c8912955554d2d8be56a51',1,'unilink::builder::TcpServerBuilder::auto_start()'],['../classunilink_1_1builder_1_1UdpClientBuilder.html#aedb2359516c75d92e1bf63060d98a5ea',1,'unilink::builder::UdpClientBuilder::auto_start()'],['../classunilink_1_1builder_1_1UdpServerBuilder.html#ac3e5e7bd408cb9f57145585f73b05129',1,'unilink::builder::UdpServerBuilder::auto_start()'],['../classunilink_1_1builder_1_1UdsServerBuilder.html#a1d677f6bc6c8c0a0eddc3f5c2cdadc1e',1,'unilink::builder::UdsServerBuilder::auto_start()']]],
  ['auto_5fstart_20true_20tt_20follows_20the_20same_20startup_20contract_91',['3. &lt;tt&gt;auto_start(true)&lt;/tt&gt; follows the same startup contract',['../contrib_arch_wrapper.html#autotoc_md248',1,'']]],
  ['autoinitializer_92',['AutoInitializer',['../classunilink_1_1builder_1_1AutoInitializer.html',1,'unilink::builder']]],
  ['automated_20integration_20coverage_93',['Automated Integration Coverage',['../contrib_orin_nano_validation.html#autotoc_md380',1,'']]],
  ['automatic_20retry_94',['Automatic Retry',['../contrib_arch.html#autotoc_md144',1,'']]],
  ['avoid_20data_20copies_95',['1. Avoid Data Copies',['../user_performance.html#autotoc_md652',1,'']]]
];
