var searchData=
[
  ['names_0',['API Names',['../contrib_design_send_result.html#autotoc_md342',1,'']]],
  ['nano_1',['Ubuntu ARM64 / Jetson Orin Nano',['../user_requirements.html#autotoc_md704',1,'']]],
  ['nano_20validation_2',['Orin Nano Validation',['../contrib_orin_nano_validation.html',1,'']]],
  ['need_20independent_20io_20thread_3',['Need independent IO thread?',['../user_quickstart.html#autotoc_md682',1,'']]],
  ['netcat_4',['Test with netcat',['../user_troubleshooting.html#autotoc_md809',1,'']]],
  ['network_20debugging_20with_20tcpdump_5',['Network Debugging with tcpdump',['../user_troubleshooting.html#autotoc_md808',1,'']]],
  ['network_20instability_6',['1. Network Instability',['../user_troubleshooting.html#autotoc_md746',1,'']]],
  ['network_20optimization_7',['Network Optimization',['../user_performance.html#autotoc_md655',1,'']]],
  ['network_20unreachable_8',['1. Network Unreachable',['../user_troubleshooting.html#autotoc_md742',1,'']]],
  ['never_20block_20in_20callbacks_9',['⚠️ Never Block in Callbacks',['../contrib_arch_runtime.html#autotoc_md181',1,'']]],
  ['next_20steps_10',['next steps',['../tutorial_02.html#autotoc_md841',1,'Next Steps'],['../tutorial_01.html#autotoc_md826',1,'Next Steps'],['../tutorial_03.html#autotoc_md854',1,'Next Steps'],['../user_quickstart.html#autotoc_md677',1,'Next Steps'],['../user_requirements.html#autotoc_md719',1,'Next Steps'],['../tutorial_04.html#autotoc_md871',1,'Next Steps'],['../tutorial_05.html#autotoc_md890',1,'Next Steps'],['../user_installation.html#autotoc_md642',1,'Next Steps'],['../contrib_testing.html#autotoc_md482',1,'Next Steps'],['../contrib_arch_memory.html#autotoc_md96',1,'Next Steps'],['../contrib_arch_runtime.html#autotoc_md243',1,'Next Steps'],['../contrib_build.html#autotoc_md335',1,'Next Steps']]],
  ['ninja_20build_20system_20faster_20than_20make_11',['Ninja Build System (Faster than Make)',['../contrib_build.html#autotoc_md311',1,'']]],
  ['no_20callbacks_20after_20stop_12',['3. Stop Semantics: No Callbacks After Stop()',['../contrib_arch_channel.html#autotoc_md5',1,'']]],
  ['no_20wrapper_20callbacks_20after_20tt_20stop_20tt_20returns_13',['7. No wrapper callbacks after &lt;tt&gt;stop()&lt;/tt&gt; returns',['../contrib_arch_wrapper.html#autotoc_md254',1,'']]],
  ['non_20blocking_20callbacks_14',['3. Non-Blocking Callbacks',['../user_performance.html#autotoc_md649',1,'']]],
  ['non_20blocking_20startup_15',['1. Non-Blocking Startup',['../user_tutorial_async.html#autotoc_md893',1,'']]],
  ['non_20goals_16',['Non-Goals',['../contrib_design_send_result.html#autotoc_md339',1,'']]],
  ['normalized_17',['8. Generic fallback errors are normalized',['../contrib_arch_wrapper.html#autotoc_md255',1,'']]],
  ['not_20being_20called_18',['Problem: Callbacks Not Being Called',['../user_troubleshooting.html#autotoc_md776',1,'']]],
  ['not_20found_19',['not found',['../contrib_orin_nano_validation.html#autotoc_md387',1,'Boost Not Found'],['../user_requirements.html#autotoc_md716',1,'Problem: Boost Not Found'],['../user_troubleshooting.html#autotoc_md765',1,'Problem: Boost Not Found'],['../contrib_build.html#autotoc_md325',1,'Problem: Compiler Not Found'],['../user_troubleshooting.html#autotoc_md756',1,'Problem: unilink/unilink.hpp Not Found']]],
  ['not_20registered_20',['1. Receive Callback Not Registered',['../user_troubleshooting.html#autotoc_md777',1,'']]],
  ['not_20running_21',['1. Server Not Running',['../user_troubleshooting.html#autotoc_md737',1,'']]],
  ['not_20set_22',['3. Keep-Alive Not Set',['../user_troubleshooting.html#autotoc_md748',1,'']]],
  ['not_20source_20stable_20before_20v1_200_23',['Internal Or Not Source-Stable Before v1.0',['../user_api_stability.html#autotoc_md606',1,'']]],
  ['not_20started_24',['2. Client Not Started',['../user_troubleshooting.html#autotoc_md778',1,'']]],
  ['notes_25',['notes',['../contrib_design.html',1,'Design Notes'],['../contrib_index.html#autotoc_md365',1,'Design Notes'],['../contrib_build.html#autotoc_md264',1,'Important Build Notes'],['../contrib_build.html#autotoc_md300',1,'Notes'],['../contrib_test_structure.html#autotoc_md407',1,'Notes'],['../tutorial_03.html#autotoc_md852',1,'Operational Notes'],['../user_installation.html#autotoc_md640',1,'Packaging Notes'],['../user_transport_matrix.html#autotoc_md730',1,'Platform Notes'],['../user_requirements.html#autotoc_md702',1,'Platform-Specific Notes'],['../tutorial_05.html#autotoc_md886',1,'Practical Notes']]],
  ['notes_20on_20uds_26',['Notes on UDS',['../user_api_guide.html#autotoc_md559',1,'']]]
];
