var searchData=
[
  ['race_20condition_20data_20corruption_0',['Problem: Race Condition / Data Corruption',['../user_troubleshooting.html#autotoc_md802',1,'']]],
  ['raii_20resource_20acquisition_20is_20initialization_1',['5. RAII (Resource Acquisition Is Initialization)',['../contrib_arch.html#autotoc_md121',1,'']]],
  ['randomly_2',['Problem: Connection Drops Randomly',['../user_troubleshooting.html#autotoc_md745',1,'']]],
  ['rate_20limiting_3',['rate limiting',['../user_api_guide.html#autotoc_md602',1,'Rate Limiting'],['../contrib_arch_runtime.html#autotoc_md217',1,'Strategy 2: Rate Limiting']]],
  ['reading_20order_4',['Recommended Reading Order',['../contrib_impl_status.html#autotoc_md359',1,'']]],
  ['real_20transport_20state_5',['1. &lt;tt&gt;start()&lt;/tt&gt; reflects real transport state',['../contrib_arch_wrapper.html#autotoc_md246',1,'']]],
  ['rebuilds_6',['Ccache for Faster Rebuilds',['../contrib_build.html#autotoc_md310',1,'']]],
  ['receive_20callback_20not_20registered_7',['1. Receive Callback Not Registered',['../user_troubleshooting.html#autotoc_md777',1,'']]],
  ['receive_20only_20listener_8',['UDP Server (Receive-only listener)',['../user_api_guide.html#autotoc_md547',1,'']]],
  ['receiver_9',['receiver',['../user_api_guide.html#autotoc_md546',1,'Echo Reply (Receiver)'],['../tutorial_05.html#autotoc_md876',1,'Step 1: Create A Receiver']]],
  ['receiver_20server_10',['UDP Receiver (Server)',['../user_api_guide.html#autotoc_md538',1,'']]],
  ['recent_5ferrors_11',['recent_errors',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#a8d203481864ef2c2f5d8e3546fcf5e38',1,'unilink::diagnostics::ErrorHandler']]],
  ['recommended_12',['recommended',['../contrib_build.html#autotoc_md262',1,'Basic Build (Recommended)'],['../user_installation.html#autotoc_md625',1,'Method 1: vcpkg (Recommended)'],['../contrib_build.html#autotoc_md295',1,'Ubuntu 22.04 (Recommended)']]],
  ['recommended_20include_20policy_13',['Recommended Include Policy',['../user_api_stability.html#autotoc_md612',1,'']]],
  ['recommended_20platform_14',['Recommended Platform',['../user_requirements.html#autotoc_md687',1,'']]],
  ['recommended_20reading_20order_15',['Recommended Reading Order',['../contrib_impl_status.html#autotoc_md359',1,'']]],
  ['reconnect_20retry_20support_16',['Reconnect / Retry Support',['../user_transport_matrix.html#autotoc_md728',1,'']]],
  ['reconnectdecision_17',['ReconnectDecision',['../structunilink_1_1ReconnectDecision.html',1,'unilink']]],
  ['reconnection_18',['Pattern 1: Auto-Reconnection',['../user_quickstart.html#autotoc_md673',1,'']]],
  ['reconnection_20best_20practices_19',['reconnection best practices',['../contrib_arch_runtime.html#autotoc_md230',1,'2. Reconnection Best Practices'],['../contrib_arch_runtime.html#autotoc_md202',1,'Reconnection Best Practices']]],
  ['reconnection_20overhead_20',['Reconnection Overhead',['../contrib_arch_runtime.html#autotoc_md240',1,'']]],
  ['reconnection_20policy_20state_20machine_21',['Reconnection Policy &amp; State Machine',['../contrib_arch_runtime.html#autotoc_md187',1,'']]],
  ['reconnectlogicdecision_22',['ReconnectLogicDecision',['../structunilink_1_1transport_1_1detail_1_1ReconnectLogicDecision.html',1,'unilink::transport::detail']]],
  ['recovery_20strategies_23',['Error Recovery Strategies',['../contrib_arch.html#autotoc_md143',1,'']]],
  ['reference_24',['reference',['../user_api_guide.html#autotoc_md553',1,'API Reference'],['../user_api_guide.html#autotoc_md540',1,'API Reference'],['../user_index.html#autotoc_md616',1,'API Reference'],['../user_api_guide.html#autotoc_md527',1,'API Reference'],['../user_api_guide.html#autotoc_md516',1,'API Reference'],['../user_api_guide.html#autotoc_md506',1,'API Reference'],['../contrib_build.html#autotoc_md271',1,'Build Options Reference'],['../user_index.html#autotoc_md617',1,'Generated Doxygen API Reference']]],
  ['reference_20to_20unilink_20symbols_25',['Problem: Undefined Reference to unilink Symbols',['../user_troubleshooting.html#autotoc_md761',1,'']]],
  ['reflects_20real_20transport_20state_26',['1. &lt;tt&gt;start()&lt;/tt&gt; reflects real transport state',['../contrib_arch_wrapper.html#autotoc_md246',1,'']]],
  ['refused_27',['Problem: Connection Refused',['../user_troubleshooting.html#autotoc_md736',1,'']]],
  ['register_5fcallback_28',['register_callback',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#af0b34d289b01281f75ce494b6ca44587',1,'unilink::diagnostics::ErrorHandler']]],
  ['registered_29',['registered',['../user_troubleshooting.html#autotoc_md777',1,'1. Receive Callback Not Registered'],['../contrib_test_structure.html#autotoc_md406',1,'Inspect What Is Currently Registered']]],
  ['registered_20tests_30',['Run All Registered Tests',['../contrib_test_structure.html#autotoc_md403',1,'']]],
  ['registration_20policy_31',['Callback Registration Policy',['../user_api_guide.html#autotoc_md495',1,'']]],
  ['regression_20testing_32',['Performance Regression Testing',['../contrib_testing.html#autotoc_md476',1,'']]],
  ['related_20docs_33',['Related Docs',['../contrib_orin_nano_validation.html#autotoc_md391',1,'']]],
  ['relationship_20to_20runtimestats_34',['Relationship To RuntimeStats',['../contrib_design_send_result.html#autotoc_md346',1,'']]],
  ['release_35',['Zero Overhead in Release',['../contrib_arch_memory.html#autotoc_md52',1,'']]],
  ['release_20assets_36',['5. Release Assets',['../contrib_release_checklist.html#autotoc_md396',1,'']]],
  ['release_20build_20default_37',['Release Build (Default)',['../contrib_build.html#autotoc_md277',1,'']]],
  ['release_20checklist_38',['Release Checklist',['../contrib_release_checklist.html',1,'']]],
  ['release_20checks_39',['7. Post-Release Checks',['../contrib_release_checklist.html#autotoc_md398',1,'']]],
  ['release_20packages_40',['Method 3: Release Packages',['../user_installation.html#autotoc_md633',1,'']]],
  ['reliable_41',['Reliable',['../user_api_guide.html#autotoc_md591',1,'']]],
  ['reliable_20data_42',['3. Critical Reliable Data',['../user_performance.html#autotoc_md663',1,'']]],
  ['reliable_20semantics_43',['Reliable Semantics',['../contrib_design_send_result.html#autotoc_md344',1,'']]],
  ['reliable_20strategy_20still_20drops_20packets_44',['Problem: UDP with Reliable Strategy Still Drops Packets',['../user_troubleshooting.html#autotoc_md781',1,'']]],
  ['reload_5ffrom_5fenvironment_45',['reload_from_environment',['../classunilink_1_1diagnostics_1_1Logger.html#a539db77422bfd1df0b1dcf27aa6a31bd',1,'unilink::diagnostics::Logger']]],
  ['relwithdebinfo_20build_46',['RelWithDebInfo Build',['../contrib_build.html#autotoc_md281',1,'']]],
  ['repeated_20testing_47',['Use The Full Examples For Repeated Testing',['../tutorial_05.html#autotoc_md888',1,'']]],
  ['repeated_20tt_20start_20tt_20and_20tt_20stop_20tt_20are_20safe_48',['2. Repeated &lt;tt&gt;start()&lt;/tt&gt; and &lt;tt&gt;stop()&lt;/tt&gt; are safe',['../contrib_arch_wrapper.html#autotoc_md247',1,'']]],
  ['replacement_20uses_20the_20latest_20callback_49',['6. Handler replacement uses the latest callback',['../contrib_arch_wrapper.html#autotoc_md253',1,'']]],
  ['reply_20receiver_50',['Echo Reply (Receiver)',['../user_api_guide.html#autotoc_md546',1,'']]],
  ['report_51',['report',['../contrib_testing.html#autotoc_md479',1,'Generate Coverage Report'],['../contrib_testing.html#autotoc_md480',1,'View HTML Coverage Report']]],
  ['report_5fcommunication_5ferror_52',['report_communication_error',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#a5b7a4963a80bfaa872fd54ff9744c05a',1,'unilink::diagnostics::error_reporting']]],
  ['report_5fconfiguration_5ferror_53',['report_configuration_error',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#a3c203bfeff57e2f08d7a29383e05d367',1,'unilink::diagnostics::error_reporting']]],
  ['report_5fconnection_5ferror_54',['report_connection_error',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#a7f2b308de562edc3c4c1d821b9a65f5e',1,'unilink::diagnostics::error_reporting']]],
  ['report_5ferror_55',['report_error',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#a4d9d47608f99b5aae760da45c784cf17',1,'unilink::diagnostics::ErrorHandler']]],
  ['report_5finfo_56',['report_info',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#aec3a25238bc1d00b9f7f509b9f6c0616',1,'unilink::diagnostics::error_reporting']]],
  ['report_5fmemory_5ferror_57',['report_memory_error',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#a3afe71d736336fb74d5882a148c87fd2',1,'unilink::diagnostics::error_reporting']]],
  ['report_5fsystem_5ferror_58',['report_system_error',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#a95bf341a9495f4cc97de408b5b02fd3f',1,'unilink::diagnostics::error_reporting']]],
  ['report_5fwarning_59',['report_warning',['../namespaceunilink_1_1diagnostics_1_1error__reporting.html#a09062defd8d7c3c8b916320c34338040',1,'unilink::diagnostics::error_reporting']]],
  ['reports_60',['4. Debug Reports',['../contrib_arch_memory.html#autotoc_md50',1,'']]],
  ['repository_20managed_20vcpkg_20setup_61',['Option A: Repository-managed vcpkg setup',['../user_installation.html#autotoc_md629',1,'']]],
  ['requirements_62',['requirements',['../user_requirements.html#autotoc_md694',1,'Compiler Requirements'],['../user_requirements.html#autotoc_md698',1,'Runtime Requirements'],['../user_requirements.html#autotoc_md686',1,'System Requirements'],['../user_requirements.html',1,'System Requirements']]],
  ['reserve_20vector_20capacity_63',['2. Reserve Vector Capacity',['../user_performance.html#autotoc_md653',1,'']]],
  ['reset_64',['reset',['../structunilink_1_1diagnostics_1_1ErrorStats.html#a9a2c2548112f8543517e601afabc5edd',1,'unilink::diagnostics::ErrorStats::reset()'],['../classunilink_1_1framer_1_1PacketFramer.html#afffae9e1300071518b560a64c0afdb9b',1,'unilink::framer::PacketFramer::reset()'],['../classunilink_1_1framer_1_1LineFramer.html#a0d7d8cead7df0c4f2d771d7fe99fe3a3',1,'unilink::framer::LineFramer::reset()'],['../classunilink_1_1framer_1_1IFramer.html#a1327792eccce0ce35f8c6b51e3fb24fd',1,'unilink::framer::IFramer::reset()']]],
  ['reset_5fstats_65',['reset_stats',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#ab8b186b9c946cc2f1ac628e704ec1846',1,'unilink::diagnostics::ErrorHandler']]],
  ['resource_20acquisition_20is_20initialization_66',['5. RAII (Resource Acquisition Is Initialization)',['../contrib_arch.html#autotoc_md121',1,'']]],
  ['responsibilities_67',['Layer Responsibilities',['../contrib_arch.html#autotoc_md104',1,'']]],
  ['results_68',['results',['../user_performance.html#autotoc_md661',1,'Interpreting Strategy Results'],['../contrib_design_send_result.html#autotoc_md348',1,'Server Send Results'],['../contrib_testing.html#autotoc_md455',1,'View CI/CD Results']]],
  ['retries_69',['2. Too Many Retries',['../user_troubleshooting.html#autotoc_md786',1,'']]],
  ['retry_70',['retry',['../user_troubleshooting.html#autotoc_md753',1,'3. Enable Port Retry'],['../contrib_arch.html#autotoc_md144',1,'Automatic Retry'],['../user_api_guide.html#autotoc_md522',1,'Port Retry']]],
  ['retry_20behavior_71',['Retry Behavior',['../contrib_arch_runtime.html#autotoc_md194',1,'']]],
  ['retry_20interval_72',['1. Choose Appropriate Retry Interval',['../contrib_arch_runtime.html#autotoc_md203',1,'']]],
  ['retry_20interval_20configuration_73',['Retry Interval Configuration',['../contrib_arch_runtime.html#autotoc_md196',1,'']]],
  ['retry_20intervals_74',['3. Set Appropriate Retry Intervals',['../user_api_guide.html#autotoc_md580',1,'']]],
  ['retry_20support_75',['Reconnect / Retry Support',['../user_transport_matrix.html#autotoc_md728',1,'']]],
  ['returns_76',['7. No wrapper callbacks after &lt;tt&gt;stop()&lt;/tt&gt; returns',['../contrib_arch_wrapper.html#autotoc_md254',1,'']]],
  ['reuse_77',['2. Connection Reuse',['../user_performance.html#autotoc_md657',1,'']]],
  ['reused_78',['4. Externally supplied &lt;tt&gt;io_context&lt;/tt&gt; can be reused',['../contrib_arch_wrapper.html#autotoc_md250',1,'']]],
  ['rules_79',['rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'5. Managed and unmanaged external contexts have different ownership rules'],['../contrib_arch_wrapper.html#autotoc_md245',1,'Core Rules']]],
  ['run_80',['Step 3: Build And Run',['../tutorial_04.html#autotoc_md863',1,'']]],
  ['run_20against_20a_20test_20server_81',['Step 3: Run Against A Test Server',['../tutorial_01.html#autotoc_md820',1,'']]],
  ['run_20all_20registered_20tests_82',['Run All Registered Tests',['../contrib_test_structure.html#autotoc_md403',1,'']]],
  ['run_20all_20tests_83',['run all tests',['../contrib_testing.html#autotoc_md413',1,'Build and Run All Tests'],['../contrib_testing.html#autotoc_md418',1,'Run All Tests']]],
  ['run_20both_20programs_84',['Step 4: Run Both Programs',['../tutorial_05.html#autotoc_md882',1,'']]],
  ['run_20by_20broad_20category_85',['Run By Broad Category',['../contrib_test_structure.html#autotoc_md404',1,'']]],
  ['run_20c_20tests_86',['Run C++ Tests',['../contrib_orin_nano_validation.html#autotoc_md377',1,'']]],
  ['run_20focused_20tests_87',['Run Focused Tests',['../contrib_build.html#autotoc_md320',1,'']]],
  ['run_20it_88',['Step 2: Run It',['../tutorial_02.html#autotoc_md833',1,'']]],
  ['run_20specific_20test_20categories_89',['Run Specific Test Categories',['../contrib_testing.html#autotoc_md420',1,'']]],
  ['run_20tests_20in_20parallel_90',['Run Tests in Parallel',['../contrib_testing.html#autotoc_md424',1,'']]],
  ['run_20tests_20with_20verbose_20output_91',['Run Tests with Verbose Output',['../contrib_testing.html#autotoc_md422',1,'']]],
  ['run_20unit_20tests_92',['Run Unit Tests',['../contrib_build.html#autotoc_md319',1,'']]],
  ['running_93',['1. Server Not Running',['../user_troubleshooting.html#autotoc_md737',1,'']]],
  ['running_20custom_20tests_94',['Running Custom Tests',['../contrib_testing.html#autotoc_md462',1,'']]],
  ['running_20tests_95',['running tests',['../contrib_test_structure.html#autotoc_md402',1,'Running Tests'],['../contrib_testing.html#autotoc_md417',1,'Running Tests']]],
  ['running_20with_20asan_96',['Running with ASan',['../contrib_arch_memory.html#autotoc_md59',1,'']]],
  ['runs_97',['Useful Focused Runs',['../contrib_test_structure.html#autotoc_md405',1,'']]],
  ['runtime_20behavior_20model_98',['Runtime Behavior Model',['../contrib_arch_runtime.html',1,'contrib_arch']]],
  ['runtime_20configuration_99',['Runtime Configuration',['../contrib_arch.html#autotoc_md148',1,'']]],
  ['runtime_20errors_100',['Runtime Errors',['../user_troubleshooting.html#autotoc_md771',1,'']]],
  ['runtime_20methods_101',['runtime methods',['../contrib_arch.html#autotoc_md127',1,'1. Runtime Methods'],['../contrib_arch_runtime.html#autotoc_md177',1,'Concurrent Runtime Methods']]],
  ['runtime_20optimization_102',['Runtime Optimization',['../user_performance.html#autotoc_md646',1,'']]],
  ['runtime_20requirements_103',['Runtime Requirements',['../user_requirements.html#autotoc_md698',1,'']]],
  ['runtime_20statistics_104',['Runtime Statistics',['../user_api_guide.html#autotoc_md594',1,'']]],
  ['runtime_20statistics_20support_105',['Runtime Statistics Support',['../user_transport_matrix.html#autotoc_md726',1,'']]],
  ['runtimestats_106',['runtimestats',['../contrib_design_send_result.html#autotoc_md346',1,'Relationship To RuntimeStats'],['../structunilink_1_1wrapper_1_1RuntimeStats.html',1,'unilink::wrapper::RuntimeStats']]],
  ['runtimestatscounters_107',['RuntimeStatsCounters',['../structunilink_1_1diagnostics_1_1RuntimeStatsCounters.html',1,'unilink::diagnostics']]]
];
