var searchData=
[
  ['i_20o_0',['1. Asynchronous I/O',['../contrib_arch.html#autotoc_md151',1,'']]],
  ['identityprojection_1',['IdentityProjection',['../structunilink_1_1transport_1_1queue__util_1_1IdentityProjection.html',1,'unilink::transport::queue_util']]],
  ['idle_5ftimeout_2',['idle_timeout',['../classunilink_1_1wrapper_1_1UdpServer.html#a43c453ae00e3861bfdb0e83e562db4a7',1,'unilink::wrapper::UdpServer::idle_timeout()'],['../classunilink_1_1wrapper_1_1TcpServer.html#a8d1309bfe7e5bbc89da2f4ca95fd84d6',1,'unilink::wrapper::TcpServer::idle_timeout()'],['../classunilink_1_1wrapper_1_1TcpClient.html#aeb705e8ec3269f0b732d3ec273ff2e85',1,'unilink::wrapper::TcpClient::idle_timeout()'],['../classunilink_1_1builder_1_1UdpServerBuilder.html#a3b9fabec12897d5255d8e54cfda298e5',1,'unilink::builder::UdpServerBuilder::idle_timeout()'],['../classunilink_1_1builder_1_1TcpServerBuilder.html#aa9ffee3f3e45da61a01c4bacc24f65d3',1,'unilink::builder::TcpServerBuilder::idle_timeout()'],['../classunilink_1_1builder_1_1TcpClientBuilder.html#acd38b067e7c98388878b6872ae1dd251',1,'unilink::builder::TcpClientBuilder::idle_timeout()']]],
  ['idle_5ftimeout_5faction_3',['idle_timeout_action',['../classunilink_1_1wrapper_1_1TcpClient.html#aecfbb5785d0f4d408c6cbf71e445a837',1,'unilink::wrapper::TcpClient::idle_timeout_action()'],['../classunilink_1_1builder_1_1TcpClientBuilder.html#a354c507b109c594560d4b8520c759d52',1,'unilink::builder::TcpClientBuilder::idle_timeout_action()']]],
  ['if_20you_20want_20more_4',['Use The Full Example If You Want More',['../tutorial_01.html#autotoc_md824',1,'']]],
  ['iframer_5',['IFramer',['../classunilink_1_1framer_1_1IFramer.html',1,'unilink::framer']]],
  ['impact_6',['Performance Impact',['../contrib_arch_memory.html#autotoc_md61',1,'']]],
  ['impl_7',['impl',['../structunilink_1_1wrapper_1_1TcpServer_1_1Impl.html',1,'unilink::wrapper::TcpServer::Impl'],['../structunilink_1_1concurrency_1_1IoContextManager_1_1Impl.html',1,'unilink::concurrency::IoContextManager::Impl'],['../structunilink_1_1config_1_1ConfigManager_1_1Impl.html',1,'unilink::config::ConfigManager::Impl'],['../structunilink_1_1diagnostics_1_1Logger_1_1Impl.html',1,'unilink::diagnostics::Logger::Impl'],['../structunilink_1_1transport_1_1Serial_1_1Impl.html',1,'unilink::transport::Serial::Impl'],['../structunilink_1_1transport_1_1TcpClient_1_1Impl.html',1,'unilink::transport::TcpClient::Impl'],['../structunilink_1_1transport_1_1TcpServer_1_1Impl.html',1,'unilink::transport::TcpServer::Impl'],['../structunilink_1_1transport_1_1UdpChannel_1_1Impl.html',1,'unilink::transport::UdpChannel::Impl'],['../structunilink_1_1transport_1_1UdsClient_1_1Impl.html',1,'unilink::transport::UdsClient::Impl'],['../structunilink_1_1transport_1_1UdsServer_1_1Impl.html',1,'unilink::transport::UdsServer::Impl'],['../structunilink_1_1wrapper_1_1TcpClient_1_1Impl.html',1,'unilink::wrapper::TcpClient::Impl'],['../structunilink_1_1wrapper_1_1Serial_1_1Impl.html',1,'unilink::wrapper::Serial::Impl'],['../structunilink_1_1wrapper_1_1UdsServer_1_1Impl.html',1,'unilink::wrapper::UdsServer::Impl'],['../structunilink_1_1wrapper_1_1UdsClient_1_1Impl.html',1,'unilink::wrapper::UdsClient::Impl'],['../structunilink_1_1wrapper_1_1UdpServer_1_1Impl.html',1,'unilink::wrapper::UdpServer::Impl'],['../structunilink_1_1wrapper_1_1UdpClient_1_1Impl.html',1,'unilink::wrapper::UdpClient::Impl']]],
  ['implementation_20status_8',['Implementation Status',['../contrib_impl_status.html',1,'contrib_index']]],
  ['important_20build_20notes_9',['Important Build Notes',['../contrib_build.html#autotoc_md264',1,'']]],
  ['in_20callback_10',['1. Busy Loop in Callback',['../user_troubleshooting.html#autotoc_md785',1,'']]],
  ['in_20callbacks_11',['in callbacks',['../contrib_arch_runtime.html#autotoc_md181',1,'⚠️ Never Block in Callbacks'],['../user_tutorial_async.html#autotoc_md896',1,'2. Shared Ownership in Callbacks']]],
  ['in_20cmake_12',['Step 2: Use in CMake',['../user_installation.html#autotoc_md639',1,'']]],
  ['in_20memory_20tracking_13',['in memory tracking',['../contrib_testing.html#autotoc_md440',1,'Built-in Memory Tracking'],['../contrib_arch_memory.html#autotoc_md41',1,'Built-in Memory Tracking']]],
  ['in_20parallel_14',['Run Tests in Parallel',['../contrib_testing.html#autotoc_md424',1,'']]],
  ['in_20release_15',['Zero Overhead in Release',['../contrib_arch_memory.html#autotoc_md52',1,'']]],
  ['in_20this_20tutorial_16',['API Patterns Used In This Tutorial',['../tutorial_01.html#autotoc_md822',1,'']]],
  ['in_20use_17',['in use',['../user_quickstart.html#autotoc_md681',1,'Port already in use?'],['../user_troubleshooting.html#autotoc_md750',1,'Problem: Port Already in Use']]],
  ['in_20your_20project_18',['in your project',['../user_installation.html#autotoc_md627',1,'Step 2: Use in your project'],['../user_installation.html#autotoc_md636',1,'Step 3: Use in your project'],['../user_installation.html#autotoc_md632',1,'Use in your project']]],
  ['include_20path_19',['2. Add Include Path',['../user_troubleshooting.html#autotoc_md758',1,'']]],
  ['include_20policy_20',['Recommended Include Policy',['../user_api_stability.html#autotoc_md612',1,'']]],
  ['includes_20configuration_20management_20api_21',['Full Build (includes Configuration Management API)',['../contrib_build.html#autotoc_md269',1,'']]],
  ['independent_20context_22',['Independent Context',['../contrib_arch.html#autotoc_md132',1,'']]],
  ['independent_20context_20for_20testing_20only_23',['1. Use Independent Context for Testing Only',['../user_api_guide.html#autotoc_md585',1,'']]],
  ['independent_20contexts_24',['2. Independent Contexts',['../contrib_arch.html#autotoc_md165',1,'']]],
  ['independent_20io_20thread_25',['Need independent IO thread?',['../user_quickstart.html#autotoc_md682',1,'']]],
  ['initialization_26',['initialization',['../user_tutorial_async.html#autotoc_md899',1,'3. Parallel Initialization'],['../contrib_arch.html#autotoc_md121',1,'5. RAII (Resource Acquisition Is Initialization)']]],
  ['initialize_5fcanary_5fbytes_27',['initialize_canary_bytes',['../namespaceunilink_1_1memory_1_1memory__validator.html#ac2c22d5175edc0989adef369dcdfb001',1,'unilink::memory::memory_validator']]],
  ['injection_28',['injection',['../contrib_arch.html#autotoc_md164',1,'1. Dependency Injection'],['../contrib_arch.html#autotoc_md118',1,'2. Dependency Injection']]],
  ['input_29',['Validate All Input',['../user_api_guide.html#autotoc_md601',1,'']]],
  ['inputvalidator_30',['InputValidator',['../classunilink_1_1util_1_1InputValidator.html',1,'unilink::util']]],
  ['inspect_20what_20is_20currently_20registered_31',['Inspect What Is Currently Registered',['../contrib_test_structure.html#autotoc_md406',1,'']]],
  ['instability_32',['1. Network Instability',['../user_troubleshooting.html#autotoc_md746',1,'']]],
  ['install_33',['Problem: Permission Denied During Install',['../contrib_build.html#autotoc_md327',1,'']]],
  ['install_20from_20source_34',['Method 2: Install from Source',['../user_installation.html#autotoc_md628',1,'']]],
  ['install_20prefix_35',['Step 2: Choose an install prefix',['../user_installation.html#autotoc_md635',1,'']]],
  ['install_20unilink_36',['1. Install unilink',['../user_troubleshooting.html#autotoc_md757',1,'']]],
  ['install_20via_20vcpkg_37',['Step 1: Install via vcpkg',['../user_installation.html#autotoc_md626',1,'']]],
  ['installation_38',['installation',['../contrib_build.html#autotoc_md313',1,'Installation'],['../user_quickstart.html#autotoc_md664',1,'Installation'],['../contrib_build.html#autotoc_md314',1,'System-Wide Installation']]],
  ['installation_20directory_39',['Custom Installation Directory',['../contrib_build.html#autotoc_md315',1,'']]],
  ['installation_20guide_40',['Installation Guide',['../user_installation.html',1,'user_index']]],
  ['installation_20methods_41',['Installation Methods',['../user_installation.html#autotoc_md624',1,'']]],
  ['installation_20options_42',['Installation Options',['../contrib_build.html#autotoc_md274',1,'']]],
  ['installation_20prefix_43',['Custom Installation Prefix',['../contrib_build.html#autotoc_md331',1,'']]],
  ['installed_20package_44',['Using the Installed Package',['../contrib_build.html#autotoc_md330',1,'']]],
  ['instance_45',['instance',['../classunilink_1_1diagnostics_1_1Logger.html#a2e114f7695d5aac3b9a993be97c501c9',1,'unilink::diagnostics::Logger::instance()'],['../classunilink_1_1diagnostics_1_1ErrorHandler.html#aadba4fe9b3095f294930ba66c2f26a01',1,'unilink::diagnostics::ErrorHandler::instance()']]],
  ['instance_20methods_46',['instance methods',['../user_api_guide.html#autotoc_md509',1,'Instance Methods'],['../user_api_guide.html#autotoc_md519',1,'Instance Methods'],['../user_api_guide.html#autotoc_md530',1,'Instance Methods']]],
  ['instance_20methods_20udpclient_47',['Instance Methods (UdpClient)',['../user_api_guide.html#autotoc_md544',1,'']]],
  ['instance_20methods_20uds_20client_48',['Instance Methods (UDS Client)',['../user_api_guide.html#autotoc_md557',1,'']]],
  ['instance_20methods_20uds_20server_49',['Instance Methods (UDS Server)',['../user_api_guide.html#autotoc_md558',1,'']]],
  ['instead_50',['When To Use The Example Programs Instead',['../tutorial_04.html#autotoc_md869',1,'']]],
  ['instead_20of_20tcp_51',['Why Use UDS Instead Of TCP',['../tutorial_03.html#autotoc_md850',1,'']]],
  ['integration_52',['integration',['../contrib_test_structure.html#autotoc_md408',1,'CI/CD Integration'],['../contrib_build.html#autotoc_md329',1,'CMake Package Integration'],['../contrib_arch_memory.html#autotoc_md94',1,'Continuous Integration'],['../contrib_testing.html#autotoc_md448',1,'Continuous Integration'],['../contrib_testing.html#autotoc_md449',1,'GitHub Actions Integration'],['../user_installation.html#autotoc_md637',1,'Method 4: Git Submodule Integration']]],
  ['integration_20coverage_53',['Automated Integration Coverage',['../contrib_orin_nano_validation.html#autotoc_md380',1,'']]],
  ['integration_20test_54',['Example: Custom Integration Test',['../contrib_testing.html#autotoc_md460',1,'']]],
  ['integration_20tests_55',['Integration Tests',['../contrib_arch_memory.html#autotoc_md92',1,'']]],
  ['internal_20or_20not_20source_20stable_20before_20v1_200_56',['Internal Or Not Source-Stable Before v1.0',['../user_api_stability.html#autotoc_md606',1,'']]],
  ['interpretation_57',['Throughput Interpretation',['../user_api_guide.html#autotoc_md593',1,'']]],
  ['interpreting_20strategy_20results_58',['Interpreting Strategy Results',['../user_performance.html#autotoc_md661',1,'']]],
  ['interval_59',['1. Choose Appropriate Retry Interval',['../contrib_arch_runtime.html#autotoc_md203',1,'']]],
  ['interval_20configuration_60',['Retry Interval Configuration',['../contrib_arch_runtime.html#autotoc_md196',1,'']]],
  ['intervals_61',['3. Set Appropriate Retry Intervals',['../user_api_guide.html#autotoc_md580',1,'']]],
  ['introduction_62',['1. Introduction',['../contrib_arch_channel.html#autotoc_md3',1,'']]],
  ['io_20context_63',['1. Threading Model &amp; IO Context',['../user_performance.html#autotoc_md647',1,'']]],
  ['io_20context_20management_64',['IO Context Management',['../contrib_arch.html#autotoc_md130',1,'']]],
  ['io_20context_20ownership_20advanced_65',['IO Context Ownership (advanced)',['../user_api_guide.html#autotoc_md500',1,'']]],
  ['io_20thread_66',['Need independent IO thread?',['../user_quickstart.html#autotoc_md682',1,'']]],
  ['io_5fcontext_20tt_20can_20be_20reused_67',['4. Externally supplied &lt;tt&gt;io_context&lt;/tt&gt; can be reused',['../contrib_arch_wrapper.html#autotoc_md250',1,'']]],
  ['io_5fcontext_20tt_20contract_68',['External &lt;tt&gt;io_context&lt;/tt&gt; Contract',['../contrib_arch_wrapper.html#autotoc_md249',1,'']]],
  ['io_5fcontext_5frunning_69',['io_context_running',['../classunilink_1_1builder_1_1AutoInitializer.html#a024748495636aa119cd1f4b97978ac68',1,'unilink::builder::AutoInitializer']]],
  ['iocontextmanager_70',['IoContextManager',['../classunilink_1_1concurrency_1_1IoContextManager.html',1,'unilink::concurrency']]],
  ['is_20currently_20registered_71',['Inspect What Is Currently Registered',['../contrib_test_structure.html#autotoc_md406',1,'']]],
  ['is_20different_20about_20udp_72',['What Is Different About UDP',['../tutorial_05.html#autotoc_md884',1,'']]],
  ['is_20initialization_73',['5. RAII (Resource Acquisition Is Initialization)',['../contrib_arch.html#autotoc_md121',1,'']]],
  ['is_5fadvanced_5flogging_5favailable_74',['is_advanced_logging_available',['../classunilink_1_1base_1_1PlatformInfo.html#adc048a50a3349ba1cac50fc6866a23d3',1,'unilink::base::PlatformInfo']]],
  ['is_5fexperimental_5ffeatures_5favailable_75',['is_experimental_features_available',['../classunilink_1_1base_1_1PlatformInfo.html#a9c296a7cf0745331431e38623ddf0a28',1,'unilink::base::PlatformInfo']]],
  ['is_5flatest_5foptimizations_5favailable_76',['is_latest_optimizations_available',['../classunilink_1_1base_1_1PlatformInfo.html#a991383f98dcff945c81652d4c7c56389',1,'unilink::base::PlatformInfo']]],
  ['is_5fperformance_5fmonitoring_5favailable_77',['is_performance_monitoring_available',['../classunilink_1_1base_1_1PlatformInfo.html#a24793bbfce94368d0a44a86e68cd68d0',1,'unilink::base::PlatformInfo']]],
  ['issues_78',['issues',['../user_troubleshooting.html#autotoc_md735',1,'Connection Issues'],['../user_troubleshooting.html#autotoc_md798',1,'Memory Issues'],['../contrib_testing.html#autotoc_md474',1,'Memory Issues'],['../user_troubleshooting.html#autotoc_md783',1,'Performance Issues'],['../user_troubleshooting.html#autotoc_md801',1,'Thread Safety Issues']]],
  ['it_79',['Step 2: Run It',['../tutorial_02.html#autotoc_md833',1,'']]]
];
