var searchData=
[
  ['each_0',['When to use each',['../user_api_guide.html#autotoc_md595',1,'']]],
  ['each_20area_20covers_1',['What Each Area Covers',['../contrib_test_structure.html#autotoc_md400',1,'']]],
  ['echo_20reply_20receiver_2',['Echo Reply (Receiver)',['../user_api_guide.html#autotoc_md546',1,'']]],
  ['echo_20server_20pattern_3',['Echo Server Pattern',['../user_api_guide.html#autotoc_md523',1,'']]],
  ['enable_20addresssanitizer_4',['Enable AddressSanitizer',['../contrib_arch_memory.html#autotoc_md55',1,'']]],
  ['enable_20async_20logging_5',['enable async logging',['../user_api_guide.html#autotoc_md586',1,'2. Enable Async Logging'],['../user_troubleshooting.html#autotoc_md796',1,'3. Enable Async Logging']]],
  ['enable_20core_20dumps_6',['1. Enable Core Dumps',['../user_troubleshooting.html#autotoc_md773',1,'']]],
  ['enable_20debug_20logging_7',['Enable Debug Logging',['../user_troubleshooting.html#autotoc_md806',1,'']]],
  ['enable_20logging_20for_20debugging_8',['4. Enable Logging for Debugging',['../user_api_guide.html#autotoc_md581',1,'']]],
  ['enable_20port_20retry_9',['3. Enable Port Retry',['../user_troubleshooting.html#autotoc_md753',1,'']]],
  ['enabled_10',['enabled',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#a833420426946d96942ab593753f22824',1,'unilink::diagnostics::ErrorHandler::enabled()'],['../classunilink_1_1diagnostics_1_1Logger.html#af0d271521653c3a590f00889471e7bcb',1,'unilink::diagnostics::Logger::enabled()']]],
  ['ensure_5fio_5fcontext_5frunning_11',['ensure_io_context_running',['../classunilink_1_1builder_1_1AutoInitializer.html#a4158d61c97d2450ea92796565b93b2bc',1,'unilink::builder::AutoInitializer']]],
  ['environment_12',['environment',['../user_api_guide.html#autotoc_md571',1,'Environment'],['../user_requirements.html#autotoc_md708',1,'Verifying Your Environment']]],
  ['environment_20test_13',['Quick Environment Test',['../user_requirements.html#autotoc_md712',1,'']]],
  ['environment_20variables_14',['Environment Variables',['../contrib_testing.html#autotoc_md467',1,'']]],
  ['error_20categories_15',['Error Categories',['../contrib_arch.html#autotoc_md142',1,'']]],
  ['error_20handler_16',['Setup Error Handler',['../user_api_guide.html#autotoc_md562',1,'']]],
  ['error_20handlers_17',['3. Custom Error Handlers',['../contrib_arch.html#autotoc_md158',1,'']]],
  ['error_20handling_18',['error handling',['../contrib_arch.html#autotoc_md140',1,'Error Handling'],['../user_api_guide.html#autotoc_md561',1,'Error Handling'],['../user_quickstart.html#autotoc_md674',1,'Pattern 2: Error Handling']]],
  ['error_20handling_20consistency_19',['5. Error Handling Consistency',['../contrib_arch_channel.html#autotoc_md7',1,'']]],
  ['error_20levels_20',['Error Levels',['../user_api_guide.html#autotoc_md563',1,'']]],
  ['error_20propagation_20flow_21',['Error Propagation Flow',['../contrib_arch.html#autotoc_md141',1,'']]],
  ['error_20recovery_20strategies_22',['Error Recovery Strategies',['../contrib_arch.html#autotoc_md143',1,'']]],
  ['error_20statistics_23',['Error Statistics',['../user_api_guide.html#autotoc_md564',1,'']]],
  ['error_5fcount_24',['error_count',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#ace4b78e5340d0a507a1d13250afed6f9',1,'unilink::diagnostics::ErrorHandler']]],
  ['error_5frate_25',['error_rate',['../structunilink_1_1diagnostics_1_1ErrorStats.html#a91590a1a6908541f51019338c8d30080',1,'unilink::diagnostics::ErrorStats']]],
  ['error_5fstats_26',['error_stats',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#aea30bf6218bbcf484545d02648b64144',1,'unilink::diagnostics::ErrorHandler']]],
  ['errorcontext_27',['ErrorContext',['../classunilink_1_1wrapper_1_1ErrorContext.html',1,'unilink::wrapper']]],
  ['errorhandler_28',['ErrorHandler',['../classunilink_1_1diagnostics_1_1ErrorHandler.html',1,'unilink::diagnostics']]],
  ['errorinfo_29',['errorinfo',['../structunilink_1_1diagnostics_1_1ErrorInfo.html#a286e6ccfc50ec89824ba31b67da616ce',1,'unilink::diagnostics::ErrorInfo::ErrorInfo(ErrorLevel l, ErrorCategory c, std::string_view comp, std::string_view op, std::string_view msg)'],['../structunilink_1_1diagnostics_1_1ErrorInfo.html#a48bdf1d2850c935cd787d2ae86bf2833',1,'unilink::diagnostics::ErrorInfo::ErrorInfo(ErrorLevel l, ErrorCategory c, std::string_view comp, std::string_view op, std::string_view msg, const boost::system::error_code &amp;ec, bool retry=false)'],['../structunilink_1_1diagnostics_1_1ErrorInfo.html',1,'unilink::diagnostics::ErrorInfo']]],
  ['errors_30',['errors',['../user_api_guide.html#autotoc_md578',1,'1. Always Handle Errors'],['../user_troubleshooting.html#autotoc_md755',1,'Compilation Errors'],['../user_troubleshooting.html#autotoc_md771',1,'Runtime Errors']]],
  ['errors_20are_20normalized_31',['8. Generic fallback errors are normalized',['../contrib_arch_wrapper.html#autotoc_md255',1,'']]],
  ['errors_5fby_5fcomponent_32',['errors_by_component',['../classunilink_1_1diagnostics_1_1ErrorHandler.html#a553bbc9805ffec33330fb7193c996aaa',1,'unilink::diagnostics::ErrorHandler']]],
  ['errorstats_33',['ErrorStats',['../structunilink_1_1diagnostics_1_1ErrorStats.html',1,'unilink::diagnostics']]],
  ['example_34',['example',['../user_api_guide.html#autotoc_md502',1,'Asynchronous Example'],['../contrib_arch_runtime.html#autotoc_md192',1,'Configuration Example']]],
  ['example_201_3a_20minimal_20production_20build_35',['Example 1: Minimal Production Build',['../contrib_build.html#autotoc_md284',1,'']]],
  ['example_202_3a_20development_20build_36',['Example 2: Development Build',['../contrib_build.html#autotoc_md286',1,'']]],
  ['example_203_3a_20testing_20with_20sanitizers_37',['Example 3: Testing with Sanitizers',['../contrib_build.html#autotoc_md288',1,'']]],
  ['example_204_3a_20build_20with_20custom_20boost_20location_38',['Example 4: Build with Custom Boost Location',['../contrib_build.html#autotoc_md290',1,'']]],
  ['example_205_3a_20build_20with_20specific_20compiler_39',['Example 5: Build with Specific Compiler',['../contrib_build.html#autotoc_md292',1,'']]],
  ['example_20if_20you_20want_20more_40',['Use The Full Example If You Want More',['../tutorial_01.html#autotoc_md824',1,'']]],
  ['example_20programs_20for_20more_41',['Use The Full Example Programs For More',['../tutorial_02.html#autotoc_md839',1,'']]],
  ['example_20programs_20instead_42',['When To Use The Example Programs Instead',['../tutorial_04.html#autotoc_md869',1,'']]],
  ['example_3a_20custom_20integration_20test_43',['Example: Custom Integration Test',['../contrib_testing.html#autotoc_md460',1,'']]],
  ['examples_44',['examples',['../contrib_build.html#autotoc_md283',1,'Advanced Build Examples'],['../user_api_guide.html#autotoc_md545',1,'Advanced Examples'],['../user_api_guide.html#autotoc_md510',1,'Advanced Examples'],['../user_api_guide.html#autotoc_md520',1,'Advanced Examples'],['../user_api_guide.html#autotoc_md532',1,'Advanced Examples']]],
  ['examples_20and_20tests_45',['Examples and Tests',['../index.html#autotoc_md488',1,'']]],
  ['examples_20for_20repeated_20testing_46',['Use The Full Examples For Repeated Testing',['../tutorial_05.html#autotoc_md888',1,'']]],
  ['excessive_20logging_47',['3. Excessive Logging',['../user_troubleshooting.html#autotoc_md787',1,'']]],
  ['execution_48',['Threading Model &amp; Callback Execution',['../contrib_arch_runtime.html#autotoc_md173',1,'']]],
  ['execution_20context_49',['✅ Callback Execution Context',['../contrib_arch_runtime.html#autotoc_md179',1,'']]],
  ['existing_20dependencies_50',['Option B: Plain CMake with existing dependencies',['../user_installation.html#autotoc_md630',1,'']]],
  ['existing_20process_51',['1. Kill Existing Process',['../user_troubleshooting.html#autotoc_md751',1,'']]],
  ['exits_20too_20quickly_52',['3. Application Exits Too Quickly',['../user_troubleshooting.html#autotoc_md779',1,'']]],
  ['expectations_53',['Transport-Agnostic Expectations',['../contrib_arch_wrapper.html#autotoc_md256',1,'']]],
  ['experimental_20api_54',['Phase 2: Experimental API',['../contrib_design_send_result.html#autotoc_md351',1,'']]],
  ['explicit_20lifecycle_20control_55',['2. Use Explicit Lifecycle Control',['../user_api_guide.html#autotoc_md579',1,'']]],
  ['extension_20points_56',['Extension Points',['../contrib_arch.html#autotoc_md155',1,'']]],
  ['external_20contexts_20have_20different_20ownership_20rules_57',['5. Managed and unmanaged external contexts have different ownership rules',['../contrib_arch_wrapper.html#autotoc_md251',1,'']]],
  ['external_20tt_20io_5fcontext_20tt_20contract_58',['External &lt;tt&gt;io_context&lt;/tt&gt; Contract',['../contrib_arch_wrapper.html#autotoc_md249',1,'']]],
  ['externally_20supplied_20tt_20io_5fcontext_20tt_20can_20be_20reused_59',['4. Externally supplied &lt;tt&gt;io_context&lt;/tt&gt; can be reused',['../contrib_arch_wrapper.html#autotoc_md250',1,'']]],
  ['extract_60',['Step 1: Download and extract',['../user_installation.html#autotoc_md634',1,'']]]
];
