var searchData=
[
  ['lambda_20capture_0',['With Lambda Capture',['../user_api_guide.html#autotoc_md512',1,'']]],
  ['last_5ferror_1',['last_error',['../classunilink_1_1diagnostics_1_1Logger.html#a8ca4c8619b5c63601a7870269fdefe2e',1,'unilink::diagnostics::Logger']]],
  ['latest_20callback_2',['6. Handler replacement uses the latest callback',['../contrib_arch_wrapper.html#autotoc_md253',1,'']]],
  ['latest_20validation_20snapshot_3',['Latest Validation Snapshot',['../contrib_orin_nano_validation.html#autotoc_md371',1,'']]],
  ['layer_4',['layer',['../contrib_arch.html#autotoc_md105',1,'1. Builder API Layer'],['../contrib_arch.html#autotoc_md106',1,'2. Wrapper API Layer'],['../contrib_arch.html#autotoc_md107',1,'3. Transport Layer'],['../contrib_arch.html#autotoc_md108',1,'4. Common Utilities Layer']]],
  ['layer_20responsibilities_5',['Layer Responsibilities',['../contrib_arch.html#autotoc_md104',1,'']]],
  ['layered_20architecture_6',['Layered Architecture',['../contrib_arch.html#autotoc_md103',1,'']]],
  ['layout_7',['Layout',['../contrib_test_structure.html#autotoc_md399',1,'']]],
  ['leak_20detected_8',['Problem: Memory Leak Detected',['../user_troubleshooting.html#autotoc_md799',1,'']]],
  ['leak_20detection_9',['2. Leak Detection',['../contrib_arch_memory.html#autotoc_md46',1,'']]],
  ['leaks_10',['1. Fix Memory Leaks',['../user_troubleshooting.html#autotoc_md790',1,'']]],
  ['level_11',['level',['../classunilink_1_1diagnostics_1_1Logger.html#a4a88b05c250af04b01f2a3d94473d0e3',1,'unilink::diagnostics::Logger']]],
  ['level_5frange_5fsink_12',['level_range_sink',['../classunilink_1_1diagnostics_1_1level__range__sink.html',1,'unilink::diagnostics']]],
  ['level_5fstring_13',['level_string',['../structunilink_1_1diagnostics_1_1ErrorInfo.html#a9faaa444de9d98cd0e75d6879daaaff3',1,'unilink::diagnostics::ErrorInfo']]],
  ['levels_14',['levels',['../user_api_guide.html#autotoc_md563',1,'Error Levels'],['../user_api_guide.html#autotoc_md568',1,'Log Levels'],['../contrib_arch_memory.html#autotoc_md15',1,'Safety Levels']]],
  ['library_15',['library',['../user_troubleshooting.html#autotoc_md762',1,'1. Link unilink Library'],['../contrib_index.html#autotoc_md361',1,'Building the Library']]],
  ['library_20dependencies_16',['Core Library Dependencies',['../user_requirements.html#autotoc_md691',1,'']]],
  ['library_20path_17',['2. Check Library Path',['../user_troubleshooting.html#autotoc_md763',1,'']]],
  ['library_20symbols_18',['Check Library Symbols',['../contrib_build.html#autotoc_md321',1,'']]],
  ['library_20users_19',['📖 For Library Users',['../index.html#autotoc_md484',1,'']]],
  ['lidar_20camera_20',['2. High-Throughput Sensors (LiDAR/Camera)',['../user_performance.html#autotoc_md662',1,'']]],
  ['lifecycle_20control_21',['2. Use Explicit Lifecycle Control',['../user_api_guide.html#autotoc_md579',1,'']]],
  ['lifecycle_20support_22',['Lifecycle Support',['../user_transport_matrix.html#autotoc_md722',1,'']]],
  ['limit_20buffer_20sizes_23',['3. Limit Buffer Sizes',['../user_troubleshooting.html#autotoc_md791',1,'']]],
  ['limiting_24',['limiting',['../user_api_guide.html#autotoc_md602',1,'Rate Limiting'],['../contrib_arch_runtime.html#autotoc_md217',1,'Strategy 2: Rate Limiting']]],
  ['limits_25',['limits',['../tutorial_02.html#autotoc_md837',1,'Client Limits'],['../user_api_guide.html#autotoc_md603',1,'Connection Limits']]],
  ['limits_20optional_26',['Pattern 3: Connection Limits (optional)',['../user_quickstart.html#autotoc_md675',1,'']]],
  ['lineframer_27',['lineframer',['../classunilink_1_1framer_1_1LineFramer.html',1,'unilink::framer::LineFramer'],['../classunilink_1_1framer_1_1LineFramer.html#adf5081f5c209b43f81ffdf9c8efdd37d',1,'unilink::framer::LineFramer::LineFramer()']]],
  ['link_20unilink_20library_28',['1. Link unilink Library',['../user_troubleshooting.html#autotoc_md762',1,'']]],
  ['links_20user_20docs_29',['Quick Links (User Docs)',['../contrib_index.html#autotoc_md367',1,'']]],
  ['linux_30',['Arch Linux',['../contrib_build.html#autotoc_md306',1,'']]],
  ['linux_20distributions_31',['Other Linux Distributions',['../user_requirements.html#autotoc_md706',1,'']]],
  ['listener_32',['UDP Server (Receive-only listener)',['../user_api_guide.html#autotoc_md547',1,'']]],
  ['ll_20build_33',['ll build',['../tutorial_01.html#autotoc_md814',1,'What You&apos;ll Build'],['../tutorial_02.html#autotoc_md829',1,'What You&apos;ll Build'],['../tutorial_03.html#autotoc_md844',1,'What You&apos;ll Build'],['../tutorial_04.html#autotoc_md857',1,'What You&apos;ll Build'],['../tutorial_05.html#autotoc_md874',1,'What You&apos;ll Build']]],
  ['load_20configuration_20from_20file_34',['Load Configuration from File',['../user_api_guide.html#autotoc_md574',1,'']]],
  ['local_20validation_35',['Local validation',['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2README.html#autotoc_md906',1,'']]],
  ['local_5fendpoint_36',['local_endpoint',['../classunilink_1_1transport_1_1UdpChannel.html#a0261c6b0358e2f7cc51d59a6ec293103',1,'unilink::transport::UdpChannel']]],
  ['location_37',['Example 4: Build with Custom Boost Location',['../contrib_build.html#autotoc_md290',1,'']]],
  ['log_20levels_38',['Log Levels',['../user_api_guide.html#autotoc_md568',1,'']]],
  ['logger_39',['Logger',['../classunilink_1_1diagnostics_1_1Logger.html',1,'unilink::diagnostics']]],
  ['logging_40',['logging',['../user_performance.html#autotoc_md648',1,'2. Async Logging'],['../user_api_guide.html#autotoc_md586',1,'2. Enable Async Logging'],['../user_troubleshooting.html#autotoc_md796',1,'3. Enable Async Logging'],['../user_troubleshooting.html#autotoc_md787',1,'3. Excessive Logging'],['../user_api_guide.html#autotoc_md569',1,'Async Logging'],['../user_troubleshooting.html#autotoc_md806',1,'Enable Debug Logging']]],
  ['logging_20for_20debugging_41',['4. Enable Logging for Debugging',['../user_api_guide.html#autotoc_md581',1,'']]],
  ['logging_20system_42',['Logging System',['../user_api_guide.html#autotoc_md566',1,'']]],
  ['logo_20assets_43',['unilink Logo Assets',['../md__2home_2runner_2work_2unilink-docs_2unilink-docs_2docs_2assets_2logo_2README.html',1,'']]],
  ['logrotationconfig_44',['LogRotationConfig',['../structunilink_1_1diagnostics_1_1LogRotationConfig.html',1,'unilink::diagnostics']]],
  ['long_20term_45',['Phase 4: Long-Term',['../contrib_design_send_result.html#autotoc_md353',1,'']]],
  ['loop_20in_20callback_46',['1. Busy Loop in Callback',['../user_troubleshooting.html#autotoc_md785',1,'']]],
  ['loopback_47',['Physical Loopback',['../contrib_orin_nano_validation.html#autotoc_md382',1,'']]],
  ['lts_48',['lts',['../user_requirements.html#autotoc_md705',1,'Ubuntu 20.04 LTS'],['../user_requirements.html#autotoc_md703',1,'Ubuntu 22.04 LTS']]]
];
