# Wirestead source and public header lists. Keep these explicit so packaging and
# IDE integration do not depend on globbing.

set(WIRESTEAD_SOURCES
    wirestead/transport/tcp_server/tcp_server.cc
    wirestead/transport/tcp_client/tcp_client.cc
    wirestead/transport/serial/serial.cc
    wirestead/builder/auto_initializer.cc
    wirestead/builder/serial_builder.cc
    wirestead/builder/tcp_client_builder.cc
    wirestead/builder/tcp_server_builder.cc
    wirestead/builder/udp_builder.cc
    wirestead/builder/unified_builder.cc
    wirestead/concurrency/io_context_manager.cc
    wirestead/config/config_factory.cc
    wirestead/config/config_manager.cc
    wirestead/diagnostics/error_handler.cc
    wirestead/diagnostics/exceptions.cc
    wirestead/diagnostics/logger.cc
    wirestead/factory/channel_factory.cc
    wirestead/interface/channel.cc
    wirestead/interface/itcp_acceptor.cc
    wirestead/interface/itcp_socket.cc
    wirestead/memory/memory_pool.cc
    wirestead/memory/memory_tracker.cc
    wirestead/memory/safe_data_buffer.cc
    wirestead/transport/tcp_server/boost_tcp_acceptor.cc
    wirestead/transport/tcp_server/boost_tcp_socket.cc
    wirestead/transport/tcp_server/tcp_server_session.cc
    wirestead/transport/udp/udp.cc
    wirestead/transport/uds/boost_uds_acceptor.cc
    wirestead/transport/uds/boost_uds_socket.cc
    wirestead/transport/uds/uds_client.cc
    wirestead/transport/uds/uds_server.cc
    wirestead/transport/uds/uds_server_session.cc
    wirestead/util/input_validator.cc
    wirestead/wrapper/serial/serial.cc
    wirestead/wrapper/tcp_client/tcp_client.cc
    wirestead/wrapper/tcp_server/tcp_server.cc
    wirestead/wrapper/udp/udp.cc
    wirestead/wrapper/udp/udp_server.cc
    wirestead/wrapper/uds_client/uds_client.cc
    wirestead/wrapper/uds_server/uds_server.cc
    wirestead/builder/uds_builder.cc
    wirestead/framer/line_framer.cc
    wirestead/framer/packet_framer.cc
)

set(WIRESTEAD_HEADERS
    wirestead/base/common.hpp
    wirestead/base/constants.hpp
    wirestead/base/deprecated.hpp
    wirestead/base/platform.hpp
    wirestead/base/visibility.hpp
    wirestead/compat/unilink.hpp
    wirestead/framer/iframer.hpp
    wirestead/framer/line_framer.hpp
    wirestead/framer/packet_framer.hpp
    wirestead/builder/auto_initializer.hpp
    wirestead/builder/ibuilder.hpp
    wirestead/builder/serial_builder.hpp
    wirestead/builder/tcp_client_builder.hpp
    wirestead/builder/tcp_server_builder.hpp
    wirestead/builder/udp_builder.hpp
    wirestead/builder/uds_builder.hpp
    wirestead/builder/unified_builder.hpp
    wirestead/concurrency/io_context_manager.hpp
    wirestead/concurrency/thread_safe_state.hpp
    wirestead/config/config_factory.hpp
    wirestead/config/config_manager.hpp
    wirestead/config/iconfig_manager.hpp
    wirestead/config/serial_config.hpp
    wirestead/config/tcp_client_config.hpp
    wirestead/config/tcp_server_config.hpp
    wirestead/config/udp_config.hpp
    wirestead/config/uds_config.hpp
    wirestead/diagnostics/error_handler.hpp
    wirestead/diagnostics/error_types.hpp
    wirestead/diagnostics/exceptions.hpp
    wirestead/diagnostics/logger.hpp
    wirestead/diagnostics/runtime_stats_counter.hpp
    wirestead/factory/channel_factory.hpp
    wirestead/interface/channel.hpp
    wirestead/interface/iserial_port.hpp
    wirestead/interface/itcp_acceptor.hpp
    wirestead/interface/itcp_resolver.hpp
    wirestead/interface/itcp_socket.hpp
    wirestead/interface/itimer.hpp
    wirestead/interface/iuds_acceptor.hpp
    wirestead/interface/iuds_socket.hpp
    wirestead/memory/memory_pool.hpp
    wirestead/memory/memory_tracker.hpp
    wirestead/memory/memory_validator.hpp
    wirestead/memory/safe_data_buffer.hpp
    wirestead/memory/safe_span.hpp
    wirestead/transport/serial/boost_serial_port.hpp
    wirestead/transport/serial/serial.hpp
    wirestead/transport/base/bp_utils.hpp
    wirestead/transport/base/reconnect_policy.hpp
    wirestead/transport/tcp_client/tcp_client.hpp
    wirestead/transport/tcp_server/boost_tcp_acceptor.hpp
    wirestead/transport/tcp_server/boost_tcp_socket.hpp
    wirestead/transport/tcp_server/tcp_server_session.hpp
    wirestead/transport/tcp_server/tcp_server.hpp
    wirestead/transport/udp/udp.hpp
    wirestead/transport/uds/boost_uds_acceptor.hpp
    wirestead/transport/uds/boost_uds_socket.hpp
    wirestead/transport/uds/uds_client.hpp
    wirestead/transport/uds/uds_server.hpp
    wirestead/transport/uds/uds_server_session.hpp
    wirestead/wirestead.hpp
    wirestead/util/input_validator.hpp
    wirestead/wrapper/ichannel.hpp
    wirestead/wrapper/runtime_stats.hpp
    wirestead/wrapper/serial/serial.hpp
    wirestead/wrapper/tcp_client/tcp_client.hpp
    wirestead/wrapper/tcp_server/tcp_server.hpp
    wirestead/wrapper/udp/udp.hpp
    wirestead/wrapper/uds_client/uds_client.hpp
    wirestead/wrapper/uds_server/uds_server.hpp
)
